/*
 * PROJECT:     ReactOS Display Driver Model
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     Dxgkrnl callbacks header
 * COPYRIGHT:   Copyright 2023 Justin Miller <justin.miller@reactos.org>
 */

#pragma once

#include <d3dkmddi.h>

/*
 * Every structure in here is shared across two or more modules and doesn't currently
 * match a single Windows version/update.
 *
 * These structures DO have variants in Windows, I just would like to track what
 * we don't match 1:1 yet. Or haven't bother attempting to do so.
 */

/* REACTOS_WIN32K_DXGKRNL_INTERFACE function Pointers: */

/*
 * Not a D3DKMT entry point - a ReactOS addition. Reports how many display adapters have finished
 * DxgkDdiStartDevice, i.e. how many displays WDDM can actually drive right now. win32k needs this
 * to decide whether to use the CDD at all: dxgkrnl.sys loads on every boot, so "dxgkrnl answered"
 * says nothing about whether a WDDM miniport was ever installed.
 */
typedef
NTSTATUS
NTAPI
DXGADAPTER_GETADAPTERCOUNT(_Out_ ULONG* unnamedParam1);

typedef DXGADAPTER_GETADAPTERCOUNT *PDXGADAPTER_GETADAPTERCOUNT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CREATEALLOCATION(_Inout_ D3DKMT_CREATEALLOCATION* unnamedParam1);

typedef DXGADAPTER_CREATEALLOCATION *PDXGADAPTER_CREATEALLOCATION;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CHECKMONITORPOWERSTATE(_In_ const D3DKMT_CHECKMONITORPOWERSTATE* unnamedParam1);

typedef DXGADAPTER_CHECKMONITORPOWERSTATE *PDXGADAPTER_CHECKMONITORPOWERSTATE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CHECKOCCLUSION(_In_ const D3DKMT_CHECKOCCLUSION* unnamedParam1);

typedef DXGADAPTER_CHECKOCCLUSION *PDXGADAPTER_CHECKOCCLUSION;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CLOSEADAPTER(_In_ const D3DKMT_CLOSEADAPTER* unnamedParam1);

typedef DXGADAPTER_CLOSEADAPTER *PDXGADAPTER_CLOSEADAPTER;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CREATECONTEXT(_Inout_ const D3DKMT_CREATECONTEXT* unnamedParam1);

typedef DXGADAPTER_CREATECONTEXT *PDXGADAPTER_CREATECONTEXT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CREATEDEVICE(_Inout_ const D3DKMT_CREATEDEVICE* unnamedParam1);

typedef DXGADAPTER_CREATEDEVICE *PDXGADAPTER_CREATEDEVICE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CREATEOVERLAY(_Inout_ const D3DKMT_CREATEOVERLAY* unnamedParam1);

typedef DXGADAPTER_CREATEOVERLAY *PDXGADAPTER_CREATEOVERLAY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_CREATESYNCHRONIZATIONOBJECT(_Inout_ const D3DKMT_CREATESYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_CREATESYNCHRONIZATIONOBJECT *PDXGADAPTER_CREATESYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_DESTROYALLOCATION(_In_ const D3DKMT_DESTROYALLOCATION* unnamedParam1);

typedef DXGADAPTER_DESTROYALLOCATION *PDXGADAPTER_DESTROYALLOCATION;

typedef
NTSTATUS
NTAPI
DXGADAPTER_DESTROYCONTEXT(_In_ const D3DKMT_DESTROYCONTEXT* unnamedParam1);

typedef DXGADAPTER_DESTROYCONTEXT *PDXGADAPTER_DESTROYCONTEXT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_DESTROYDEVICE(_In_ const D3DKMT_DESTROYDEVICE* unnamedParam1);

typedef DXGADAPTER_DESTROYDEVICE *PDXGADAPTER_DESTROYDEVICE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_DESTROYOVERLAY(_In_ const D3DKMT_DESTROYOVERLAY* unnamedParam1);

typedef DXGADAPTER_DESTROYOVERLAY *PDXGADAPTER_DESTROYOVERLAY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_DESTROYSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT *PDXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_ESCAPE(_In_ const D3DKMT_ESCAPE* unnamedParam1);

typedef DXGADAPTER_ESCAPE *PDXGADAPTER_ESCAPE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_FLIPOVERLAY(_In_ const D3DKMT_FLIPOVERLAY* unnamedParam1);

typedef DXGADAPTER_FLIPOVERLAY *PDXGADAPTER_FLIPOVERLAY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY(_Inout_ const D3DKMT_GETCONTEXTSCHEDULINGPRIORITY* unnamedParam1);

typedef DXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY *PDXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETDEVICESTATE(_Inout_ D3DKMT_GETDEVICESTATE* unnamedParam1);

typedef DXGADAPTER_GETDEVICESTATE *PDXGADAPTER_GETDEVICESTATE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETDISPLAYMODELIST(_Inout_ D3DKMT_GETDISPLAYMODELIST* unnamedParam1);

typedef DXGADAPTER_GETDISPLAYMODELIST *PDXGADAPTER_GETDISPLAYMODELIST;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETMULTISAMPLEMETHODLIST(_Inout_ D3DKMT_GETMULTISAMPLEMETHODLIST* unnamedParam1);

typedef DXGADAPTER_GETMULTISAMPLEMETHODLIST *PDXGADAPTER_GETMULTISAMPLEMETHODLIST;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETRUNTIMEDATA(_Inout_ const D3DKMT_GETRUNTIMEDATA* unnamedParam1);

typedef DXGADAPTER_GETRUNTIMEDATA *PDXGADAPTER_GETRUNTIMEDATA;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETSCANLINE(_Inout_ D3DKMT_GETSCANLINE* unnamedParam1);

typedef DXGADAPTER_GETSCANLINE *PDXGADAPTER_GETSCANLINE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT *PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_WAITFORVERTICALBLANKEVENT(_In_ const D3DKMT_WAITFORVERTICALBLANKEVENT* unnamedParam1);

typedef DXGADAPTER_WAITFORVERTICALBLANKEVENT *PDXGADAPTER_WAITFORVERTICALBLANKEVENT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT *PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETVIDPNSOURCEOWNER(_In_ const D3DKMT_SETVIDPNSOURCEOWNER* unnamedParam1);

typedef DXGADAPTER_SETVIDPNSOURCEOWNER *PDXGADAPTER_SETVIDPNSOURCEOWNER;

typedef
NTSTATUS
NTAPI
DXGADAPTER_WAITFORIDLE(_In_ const D3DKMT_WAITFORIDLE* unnamedParam1);

typedef DXGADAPTER_WAITFORIDLE *PDXGADAPTER_WAITFORIDLE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_UPDATEOVERLAY(_In_ const D3DKMT_UPDATEOVERLAY* unnamedParam1);

typedef DXGADAPTER_UPDATEOVERLAY *PDXGADAPTER_UPDATEOVERLAY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETQUEUEDLIMIT(_In_ const D3DKMT_SETQUEUEDLIMIT* unnamedParam1);

typedef DXGADAPTER_SETQUEUEDLIMIT *PDXGADAPTER_SETQUEUEDLIMIT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETGAMMARAMP(_In_ const D3DKMT_SETGAMMARAMP* unnamedParam1);

typedef DXGADAPTER_SETGAMMARAMP *PDXGADAPTER_SETGAMMARAMP;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETDISPLAYMODE(_In_ const D3DKMT_SETDISPLAYMODE* unnamedParam1);

typedef DXGADAPTER_SETDISPLAYMODE *PDXGADAPTER_SETDISPLAYMODE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT(_In_ const D3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT* unnamedParam1);

typedef DXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT *PDXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT;


typedef
NTSTATUS
NTAPI
DXGADAPTER_SETGAMMARAMP(_In_ const D3DKMT_SETGAMMARAMP* unnamedParam1);

typedef DXGADAPTER_SETGAMMARAMP *PDXGADAPTER_SETGAMMARAMP;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETQUEUEDLIMIT(_In_ const D3DKMT_SETQUEUEDLIMIT* unnamedParam1);

typedef DXGADAPTER_SETQUEUEDLIMIT *PDXGADAPTER_SETQUEUEDLIMIT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETVIDPNSOURCEOWNER(_In_ const D3DKMT_SETVIDPNSOURCEOWNER* unnamedParam1);

typedef DXGADAPTER_SETVIDPNSOURCEOWNER *PDXGADAPTER_SETVIDPNSOURCEOWNER;

typedef
NTSTATUS
NTAPI
DXGADAPTER_UNLOCK(_In_ const D3DKMT_UNLOCK* unnamedParam1);

typedef DXGADAPTER_UNLOCK *PDXGADAPTER_UNLOCK;

typedef
NTSTATUS
NTAPI
DXGADAPTER_UPDATEOVERLAY(_In_ const D3DKMT_UPDATEOVERLAY* unnamedParam1);

typedef DXGADAPTER_UPDATEOVERLAY *PDXGADAPTER_UPDATEOVERLAY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_WAITFORIDLE(_In_ const D3DKMT_WAITFORIDLE* unnamedParam1);

typedef DXGADAPTER_WAITFORIDLE *PDXGADAPTER_WAITFORIDLE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT *PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_WAITFORVERTICALBLANKEVENT(_In_ const D3DKMT_WAITFORVERTICALBLANKEVENT* unnamedParam1);

typedef DXGADAPTER_WAITFORVERTICALBLANKEVENT *PDXGADAPTER_WAITFORVERTICALBLANKEVENT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT *PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
NTAPI
DXGADAPTER_QUERYRESOURCEINFO(_Inout_ D3DKMT_QUERYRESOURCEINFO* unnamedParam1);

typedef DXGADAPTER_QUERYRESOURCEINFO *PDXGADAPTER_QUERYRESOURCEINFO;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETPRESENTHISTORY(_Inout_ D3DKMT_GETPRESENTHISTORY* unnamedParam1);

typedef DXGADAPTER_GETPRESENTHISTORY *PDXGADAPTER_GETPRESENTHISTORY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETALLOCATIONPRIORITY(_In_ const D3DKMT_SETALLOCATIONPRIORITY* unnamedParam1);

typedef DXGADAPTER_SETALLOCATIONPRIORITY *PDXGADAPTER_SETALLOCATIONPRIORITY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_INVALIDATEACTIVEVIDPN(_In_ const D3DKMT_INVALIDATEACTIVEVIDPN* unnamedParam1);

typedef DXGADAPTER_INVALIDATEACTIVEVIDPN *PDXGADAPTER_INVALIDATEACTIVEVIDPN;

typedef
NTSTATUS
NTAPI
DXGADAPTER_GETSHAREDPRIMARYHANDLE(_In_ D3DKMT_GETSHAREDPRIMARYHANDLE* unnamedParam1);

typedef DXGADAPTER_GETSHAREDPRIMARYHANDLE *PDXGADAPTER_GETSHAREDPRIMARYHANDLE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_LOCK(_In_ D3DKMT_LOCK* unnamedParam1);

typedef DXGADAPTER_LOCK *PDXGADAPTER_LOCK;

typedef
NTSTATUS
NTAPI
DXGADAPTER_POLLDISPLAYCHILDREN(_In_ const D3DKMT_POLLDISPLAYCHILDREN* unnamedParam1);

typedef DXGADAPTER_POLLDISPLAYCHILDREN *PDXGADAPTER_POLLDISPLAYCHILDREN;

typedef
NTSTATUS
NTAPI
DXGADAPTER_OPENRESOURCE(_Inout_ D3DKMT_OPENRESOURCE* unnamedParam1);

typedef DXGADAPTER_OPENRESOURCE *PDXGADAPTER_OPENRESOURCE;

typedef
NTSTATUS
NTAPI
DXGADAPTER_PRESENT(_In_ D3DKMT_PRESENT* unnamedParam1);

typedef DXGADAPTER_PRESENT *PDXGADAPTER_PRESENT;

/*
 * The D3DKMTOpenAdapterFrom* family. These are the entry points EVERY user-mode graphics client
 * starts at - the D3D runtime and opengl32 both open an adapter and then immediately ask
 * QueryAdapterInfo for the driver DLL to load - so with no slot for them win32k's thunks had
 * nowhere to dispatch and no user-mode driver could ever be reached.
 */
typedef
NTSTATUS
NTAPI
DXGADAPTER_OPENADAPTERFROMHDC(_Inout_ D3DKMT_OPENADAPTERFROMHDC* unnamedParam1);

typedef DXGADAPTER_OPENADAPTERFROMHDC *PDXGADAPTER_OPENADAPTERFROMHDC;

typedef
NTSTATUS
NTAPI
DXGADAPTER_OPENADAPTERFROMGDIDISPLAYNAME(_Inout_ D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME* unnamedParam1);

typedef DXGADAPTER_OPENADAPTERFROMGDIDISPLAYNAME *PDXGADAPTER_OPENADAPTERFROMGDIDISPLAYNAME;

typedef
NTSTATUS
NTAPI
DXGADAPTER_OPENADAPTERFROMDEVICENAME(_Inout_ D3DKMT_OPENADAPTERFROMDEVICENAME* unnamedParam1);

typedef DXGADAPTER_OPENADAPTERFROMDEVICENAME *PDXGADAPTER_OPENADAPTERFROMDEVICENAME;

typedef
NTSTATUS
NTAPI
DXGADAPTER_QUERYADAPTERINFO(_Inout_ const D3DKMT_QUERYADAPTERINFO* unnamedParam1);

typedef DXGADAPTER_QUERYADAPTERINFO *PDXGADAPTER_QUERYADAPTERINFO;

typedef
NTSTATUS
NTAPI
DXGADAPTER_QUERYALLOCATIONRESIDENCY(_In_ const D3DKMT_QUERYALLOCATIONRESIDENCY* unnamedParam1);

typedef DXGADAPTER_QUERYALLOCATIONRESIDENCY *PDXGADAPTER_QUERYALLOCATIONRESIDENCY;

typedef
NTSTATUS
NTAPI
DXGADAPTER_QUERYSTATISTICS(_Inout_ const D3DKMT_QUERYSTATISTICS* unnamedParam1);

typedef DXGADAPTER_QUERYSTATISTICS *PDXGADAPTER_QUERYSTATISTICS;

typedef
NTSTATUS
NTAPI
DXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS(_In_ HANDLE unnamedParam1);

typedef DXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS *PDXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS;

typedef
NTSTATUS
NTAPI
DXGADAPTER_RENDER(_In_ D3DKMT_RENDER* unnamedParam1);

typedef DXGADAPTER_RENDER *PDXGADAPTER_RENDER;

typedef
NTSTATUS
NTAPI
DXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY(_In_ const D3DKMT_SETCONTEXTSCHEDULINGPRIORITY* unnamedParam1);

typedef DXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY *PDXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY;

/*
 * This structure is the callbacks list that exist between DXGKNRL and Win32k.
 * This private interface is undocumented and changes with every Windows update
 * that remotely touches WDDM.
 *
 * Reversing this isn't possible until we can throw our DxgKrnl into vista or above at runtime.
 * But this cannot happen without us first supporting watchdog.
 */
typedef struct _REACTOS_WIN32K_DXGKRNL_INTERFACE
{
    PDXGADAPTER_PRESENT RxgkIntPfnPresent;
    PDXGADAPTER_QUERYADAPTERINFO RxgkIntPfnQueryAdapterInfo;
    PDXGADAPTER_QUERYALLOCATIONRESIDENCY RxgkIntPfnQueryAllocationResidency;
    PDXGADAPTER_QUERYSTATISTICS RxgkIntPfnQueryStatistics;
    PDXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS RxgkIntPfnReleaseProcessVidPnSourceOwners;
    PDXGADAPTER_RENDER RxgkIntPfnRender;
    PDXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY RxgkIntPfnSetContextSchedulingPriority;
    PDXGADAPTER_OPENRESOURCE RxgkIntPfnOpenResource;
    PDXGADAPTER_POLLDISPLAYCHILDREN RxgkIntPfnPollDisplayChildren;
    PDXGADAPTER_LOCK RxgkIntPfnLock;
    PDXGADAPTER_GETSHAREDPRIMARYHANDLE RxgkIntPfnGetSharedPrimaryHandle;
    PDXGADAPTER_INVALIDATEACTIVEVIDPN RxgkIntPfnInvalidateActiveVidPn;
    PDXGADAPTER_SETALLOCATIONPRIORITY RxgkIntPfnSetAllocationPriority;
    PDXGADAPTER_GETPRESENTHISTORY RxgkIntPfnGetPresentHistory;
    PDXGADAPTER_QUERYRESOURCEINFO RxgkIntPfnQueryResourceInfo;
    PDXGADAPTER_CREATEALLOCATION RxgkIntPfnCreateAllocation;
    PDXGADAPTER_CHECKMONITORPOWERSTATE RxgkIntPfnCheckMonitorPowerState;
    PDXGADAPTER_CHECKOCCLUSION RxgkIntPfnCheckOcclusion;
    PDXGADAPTER_CLOSEADAPTER RxgkIntPfnCloseAdapter;
    PDXGADAPTER_CREATECONTEXT RxgkIntPfnCreateContext;
    PDXGADAPTER_CREATEDEVICE RxgkIntPfnCreateDevice;
    PDXGADAPTER_CREATEOVERLAY RxgkIntPfnCreateOverlay;
    PDXGADAPTER_CREATESYNCHRONIZATIONOBJECT RxgkIntPfnCreateSynchronizationObject;
    PDXGADAPTER_DESTROYCONTEXT RxgkIntPfnDestroyContext;
    PDXGADAPTER_DESTROYDEVICE RxgkIntPfnDestroyDevice;
    PDXGADAPTER_DESTROYOVERLAY RxgkIntPfnDestroyOverlay;
    PDXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT RxgkIntPfnDestroySynchronizationObject;
    PDXGADAPTER_ESCAPE RxgkIntPfnEscape;
    PDXGADAPTER_DESTROYALLOCATION RxgkIntPfnDestroyAllocation;
    PDXGADAPTER_FLIPOVERLAY RxgkIntPfnFlipOverlay;
    PDXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY RxgkIntPfnGetContextSchedulingPriority;
    PDXGADAPTER_GETDEVICESTATE RxgkIntPfnGetDeviceState;
    PDXGADAPTER_GETDISPLAYMODELIST RxgkIntPfnGetDisplayModeList;
    PDXGADAPTER_GETMULTISAMPLEMETHODLIST RxgkIntPfnGetMultisampleMethodList;
    PDXGADAPTER_GETRUNTIMEDATA RxgkIntPfnGetRuntimeData;
    PDXGADAPTER_GETSCANLINE RxgkIntPfnGetScanLine;
    PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT RxgkIntPfnSignalSynchronizationObject;
    PDXGADAPTER_WAITFORVERTICALBLANKEVENT RxgkIntPfnWaitForVerticalBlankEvent;
    PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT RxgkIntPfnWaitForSynchronizationObject;
    PDXGADAPTER_SETVIDPNSOURCEOWNER RxgkIntPfnSetVidPnSourceOwner;
    PDXGADAPTER_WAITFORIDLE RxgkIntPfnWaitForIdle;
    PDXGADAPTER_UPDATEOVERLAY RxgkIntPfnUpdateOverlay;
    PDXGADAPTER_SETQUEUEDLIMIT RxgkIntPfnSetQueuedLimit;
    PDXGADAPTER_SETGAMMARAMP RxgkIntPfnSetGammaRamp;
    PDXGADAPTER_SETDISPLAYMODE RxgkIntPfnSetDisplayMode;
    PDXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT RxgkIntPfnSetDisplayPrivateDriverFormat;
    PDXGADAPTER_UNLOCK RxgkIntPfnUnlock;
    /* Appended - the adapter-open family the D3D/OpenGL runtimes enter through. */
    PDXGADAPTER_OPENADAPTERFROMHDC RxgkIntPfnOpenAdapterFromHdc;
    PDXGADAPTER_OPENADAPTERFROMGDIDISPLAYNAME RxgkIntPfnOpenAdapterFromGdiDisplayName;
    PDXGADAPTER_OPENADAPTERFROMDEVICENAME RxgkIntPfnOpenAdapterFromDeviceName;
    /* Appended - lets win32k ask whether WDDM can actually drive a display yet. */
    PDXGADAPTER_GETADAPTERCOUNT RxgkIntPfnGetAdapterCount;
} REACTOS_WIN32K_DXGKRNL_INTERFACE, *PREACTOS_WIN32K_DXGKRNL_INTERFACE;
