/*
 * PROJECT:     ReactOS NDIS 6 support
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Data structures carried by the NDIS 6 general OIDs
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef ULONG NDIS_PORT_NUMBER, *PNDIS_PORT_NUMBER;

#define NDIS_OBJECT_TYPE_CONFIGURATION_OBJECT       0xA9

#define NDIS_LINK_STATE_REVISION_1                  1
#define NDIS_STATISTICS_INFO_REVISION_1             1
#define NDIS_RSC_STATISTICS_REVISION_1              1
#define NDIS_INTERRUPT_MODERATION_PARAMETERS_REVISION_1 1
#define NDIS_CONFIGURATION_OBJECT_REVISION_1        1
#define NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES_REVISION_1 1
#define NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES_REVISION_2 2

#define NDIS_DEFAULT_PORT_NUMBER                    0

#define NDIS_MAX_PHYS_ADDRESS_LENGTH                32

#define NDIS_LINK_SPEED_UNKNOWN                     NET_IF_LINK_SPEED_UNKNOWN

/* NDIS_LINK_STATE::AutoNegotiationFlags */
#define NDIS_LINK_STATE_XMIT_LINK_SPEED_AUTO_NEGOTIATED     0x00000001
#define NDIS_LINK_STATE_RCV_LINK_SPEED_AUTO_NEGOTIATED      0x00000002
#define NDIS_LINK_STATE_DUPLEX_AUTO_NEGOTIATED              0x00000004
#define NDIS_LINK_STATE_PAUSE_FUNCTIONS_AUTO_NEGOTIATED     0x00000008

/* NDIS_STATISTICS_INFO::SupportedStatistics */
#define NDIS_STATISTICS_FLAGS_VALID_DIRECTED_FRAMES_RCV     0x00000001
#define NDIS_STATISTICS_FLAGS_VALID_MULTICAST_FRAMES_RCV    0x00000002
#define NDIS_STATISTICS_FLAGS_VALID_BROADCAST_FRAMES_RCV    0x00000004
#define NDIS_STATISTICS_FLAGS_VALID_BYTES_RCV               0x00000008
#define NDIS_STATISTICS_FLAGS_VALID_RCV_DISCARDS            0x00000010
#define NDIS_STATISTICS_FLAGS_VALID_RCV_ERROR               0x00000020
#define NDIS_STATISTICS_FLAGS_VALID_DIRECTED_FRAMES_XMIT    0x00000040
#define NDIS_STATISTICS_FLAGS_VALID_MULTICAST_FRAMES_XMIT   0x00000080
#define NDIS_STATISTICS_FLAGS_VALID_BROADCAST_FRAMES_XMIT   0x00000100
#define NDIS_STATISTICS_FLAGS_VALID_BYTES_XMIT              0x00000200
#define NDIS_STATISTICS_FLAGS_VALID_XMIT_ERROR              0x00000400
#define NDIS_STATISTICS_FLAGS_VALID_XMIT_DISCARDS           0x00008000
#define NDIS_STATISTICS_FLAGS_VALID_DIRECTED_BYTES_RCV      0x00010000
#define NDIS_STATISTICS_FLAGS_VALID_MULTICAST_BYTES_RCV     0x00020000
#define NDIS_STATISTICS_FLAGS_VALID_BROADCAST_BYTES_RCV     0x00040000
#define NDIS_STATISTICS_FLAGS_VALID_DIRECTED_BYTES_XMIT     0x00080000
#define NDIS_STATISTICS_FLAGS_VALID_MULTICAST_BYTES_XMIT    0x00100000
#define NDIS_STATISTICS_FLAGS_VALID_BROADCAST_BYTES_XMIT    0x00200000

/* NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES::SupportedStatistics */
#define NDIS_STATISTICS_XMIT_OK_SUPPORTED                   0x00000001
#define NDIS_STATISTICS_RCV_OK_SUPPORTED                    0x00000002
#define NDIS_STATISTICS_XMIT_ERROR_SUPPORTED                0x00000004
#define NDIS_STATISTICS_RCV_ERROR_SUPPORTED                 0x00000008
#define NDIS_STATISTICS_RCV_NO_BUFFER_SUPPORTED             0x00000010
#define NDIS_STATISTICS_DIRECTED_BYTES_XMIT_SUPPORTED       0x00000020
#define NDIS_STATISTICS_DIRECTED_FRAMES_XMIT_SUPPORTED      0x00000040
#define NDIS_STATISTICS_MULTICAST_BYTES_XMIT_SUPPORTED      0x00000080
#define NDIS_STATISTICS_MULTICAST_FRAMES_XMIT_SUPPORTED     0x00000100
#define NDIS_STATISTICS_BROADCAST_BYTES_XMIT_SUPPORTED      0x00000200
#define NDIS_STATISTICS_BROADCAST_FRAMES_XMIT_SUPPORTED     0x00000400
#define NDIS_STATISTICS_DIRECTED_BYTES_RCV_SUPPORTED        0x00000800
#define NDIS_STATISTICS_DIRECTED_FRAMES_RCV_SUPPORTED       0x00001000
#define NDIS_STATISTICS_MULTICAST_BYTES_RCV_SUPPORTED       0x00002000
#define NDIS_STATISTICS_MULTICAST_FRAMES_RCV_SUPPORTED      0x00004000
#define NDIS_STATISTICS_BROADCAST_BYTES_RCV_SUPPORTED       0x00008000
#define NDIS_STATISTICS_BROADCAST_FRAMES_RCV_SUPPORTED      0x00010000
#define NDIS_STATISTICS_RCV_CRC_ERROR_SUPPORTED             0x00020000
#define NDIS_STATISTICS_TRANSMIT_QUEUE_LENGTH_SUPPORTED     0x00040000
#define NDIS_STATISTICS_BYTES_RCV_SUPPORTED                 0x00080000
#define NDIS_STATISTICS_BYTES_XMIT_SUPPORTED                0x00100000
#define NDIS_STATISTICS_RCV_DISCARDS_SUPPORTED              0x00200000
#define NDIS_STATISTICS_GEN_STATISTICS_SUPPORTED            0x00400000
#define NDIS_STATISTICS_XMIT_DISCARDS_SUPPORTED             0x08000000

/* NDIS_GUID::Flags, which ntddndis.h declares the structure for. */
#define NDIS_GUID_TO_OID                            0x00000001
#define NDIS_GUID_TO_STATUS                         0x00000002
#define NDIS_GUID_ANSI_STRING                       0x00000004
#define NDIS_GUID_UNICODE_STRING                    0x00000008
#define NDIS_GUID_ARRAY                             0x00000010
#define NDIS_GUID_ALLOW_READ                        0x00000020
#define NDIS_GUID_ALLOW_WRITE                       0x00000040
#define NDIS_GUID_METHOD                            0x00000080
#define NDIS_GUID_NDIS_RESERVED                     0x00000100
#define NDIS_GUID_SUPPORT_COMMON_HEADER             0x00000200

typedef enum _NDIS_SUPPORTED_PAUSE_FUNCTIONS
{
    NdisPauseFunctionsUnsupported,
    NdisPauseFunctionsSendOnly,
    NdisPauseFunctionsReceiveOnly,
    NdisPauseFunctionsSendAndReceive,
    NdisPauseFunctionsUnknown
} NDIS_SUPPORTED_PAUSE_FUNCTIONS, *PNDIS_SUPPORTED_PAUSE_FUNCTIONS;

typedef enum _NDIS_INTERRUPT_MODERATION
{
    NdisInterruptModerationUnknown,
    NdisInterruptModerationNotSupported,
    NdisInterruptModerationEnabled,
    NdisInterruptModerationDisabled
} NDIS_INTERRUPT_MODERATION, *PNDIS_INTERRUPT_MODERATION;

typedef struct _NDIS_LINK_SPEED
{
    ULONG64 XmitLinkSpeed;
    ULONG64 RcvLinkSpeed;
} NDIS_LINK_SPEED, *PNDIS_LINK_SPEED;

typedef struct _NDIS_LINK_STATE
{
    NDIS_OBJECT_HEADER Header;
    NET_IF_MEDIA_CONNECT_STATE MediaConnectState;
    NET_IF_MEDIA_DUPLEX_STATE MediaDuplexState;
    ULONG64 XmitLinkSpeed;
    ULONG64 RcvLinkSpeed;
    NDIS_SUPPORTED_PAUSE_FUNCTIONS PauseFunctions;
    ULONG AutoNegotiationFlags;
} NDIS_LINK_STATE, *PNDIS_LINK_STATE;

#define NDIS_SIZEOF_LINK_STATE_REVISION_1 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_LINK_STATE, AutoNegotiationFlags)

typedef struct _NDIS_STATISTICS_INFO
{
    NDIS_OBJECT_HEADER Header;
    ULONG SupportedStatistics;
    ULONG64 ifInDiscards;
    ULONG64 ifInErrors;
    ULONG64 ifHCInOctets;
    ULONG64 ifHCInUcastPkts;
    ULONG64 ifHCInMulticastPkts;
    ULONG64 ifHCInBroadcastPkts;
    ULONG64 ifHCOutOctets;
    ULONG64 ifHCOutUcastPkts;
    ULONG64 ifHCOutMulticastPkts;
    ULONG64 ifHCOutBroadcastPkts;
    ULONG64 ifOutErrors;
    ULONG64 ifOutDiscards;
    ULONG64 ifHCInUcastOctets;
    ULONG64 ifHCInMulticastOctets;
    ULONG64 ifHCInBroadcastOctets;
    ULONG64 ifHCOutUcastOctets;
    ULONG64 ifHCOutMulticastOctets;
    ULONG64 ifHCOutBroadcastOctets;
} NDIS_STATISTICS_INFO, *PNDIS_STATISTICS_INFO;

#define NDIS_SIZEOF_STATISTICS_INFO_REVISION_1 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_STATISTICS_INFO, ifHCOutBroadcastOctets)

typedef struct _NDIS_RSC_STATISTICS_INFO
{
    NDIS_OBJECT_HEADER Header;
    ULONG64 CoalescedPkts;
    ULONG64 CoalescedOctets;
    ULONG64 CoalesceEvents;
    ULONG64 Aborts;
} NDIS_RSC_STATISTICS_INFO, *PNDIS_RSC_STATISTICS_INFO;

#define NDIS_SIZEOF_RSC_STATISTICS_REVISION_1 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_RSC_STATISTICS_INFO, Aborts)

typedef struct _NDIS_INTERRUPT_MODERATION_PARAMETERS
{
    NDIS_OBJECT_HEADER Header;
    ULONG Flags;
    NDIS_INTERRUPT_MODERATION InterruptModeration;
} NDIS_INTERRUPT_MODERATION_PARAMETERS, *PNDIS_INTERRUPT_MODERATION_PARAMETERS;

#define NDIS_SIZEOF_INTERRUPT_MODERATION_PARAMETERS_REVISION_1 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_INTERRUPT_MODERATION_PARAMETERS, InterruptModeration)

typedef struct _NDIS_CONFIGURATION_OBJECT
{
    NDIS_OBJECT_HEADER Header;
    NDIS_HANDLE NdisHandle;
    ULONG Flags;
} NDIS_CONFIGURATION_OBJECT, *PNDIS_CONFIGURATION_OBJECT;

#define NDIS_SIZEOF_CONFIGURATION_OBJECT_REVISION_1 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_CONFIGURATION_OBJECT, Flags)

typedef struct _NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES
{
    NDIS_OBJECT_HEADER Header;
    ULONG Flags;
    NDIS_MEDIUM MediaType;
    NDIS_PHYSICAL_MEDIUM PhysicalMediumType;
    ULONG MtuSize;
    ULONG64 MaxXmitLinkSpeed;
    ULONG64 XmitLinkSpeed;
    ULONG64 MaxRcvLinkSpeed;
    ULONG64 RcvLinkSpeed;
    NET_IF_MEDIA_CONNECT_STATE MediaConnectState;
    NET_IF_MEDIA_DUPLEX_STATE MediaDuplexState;
    ULONG LookaheadSize;
    PNDIS_PNP_CAPABILITIES PowerManagementCapabilities;
    ULONG MacOptions;
    ULONG SupportedPacketFilters;
    ULONG MaxMulticastListSize;
    USHORT MacAddressLength;
    UCHAR PermanentMacAddress[NDIS_MAX_PHYS_ADDRESS_LENGTH];
    UCHAR CurrentMacAddress[NDIS_MAX_PHYS_ADDRESS_LENGTH];
    PNDIS_RECEIVE_SCALE_CAPABILITIES RecvScaleCapabilities;
    NET_IF_ACCESS_TYPE AccessType;
    NET_IF_DIRECTION_TYPE DirectionType;
    NET_IF_CONNECTION_TYPE ConnectionType;
    NET_IFTYPE IfType;
    BOOLEAN IfConnectorPresent;
    ULONG SupportedStatistics;
    ULONG SupportedPauseFunctions;
    ULONG DataBackFillSize;
    ULONG ContextBackFillSize;
    PNDIS_OID SupportedOidList;
    ULONG SupportedOidListLength;
    ULONG AutoNegotiationFlags;
    PNDIS_PM_CAPABILITIES PowerManagementCapabilitiesEx;
} NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES, *PNDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES;

#define NDIS_SIZEOF_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES_REVISION_1 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES, AutoNegotiationFlags)
#define NDIS_SIZEOF_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES_REVISION_2 \
    RTL_SIZEOF_THROUGH_FIELD(NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES, \
                             PowerManagementCapabilitiesEx)

#ifdef __cplusplus
}
#endif
