# Generate armasm64 thunks for rpcrt4 (ObjectStublessClient3..1023, NdrProxyForwardingFunction3..1023).
import os

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "thunks-msvc.asm")
lines = [
    "; Auto-generated by gen_thunks_msvc_asm.py — MSVC ARM64 rpcrt4 thunks",
    "    IMPORT call_stubless_func",
    "    AREA    |.text|, CODE, READONLY, ALIGN=4",
    "    EXPORT stubless_thunks",
    "stubless_thunks",
]
for i in range(3, 1024):
    lines += [
        "    ALIGN 4",
        f"    EXPORT ObjectStublessClient{i}",
        f"ObjectStublessClient{i}",
        f"    mov     w16, #{i}",
        "    b       call_stubless_func",
    ]
lines += [
    "    EXPORT vtbl_thunks",
    "vtbl_thunks",
]
for i in range(3, 1024):
    lines += [
        "    ALIGN 4",
        f"    EXPORT NdrProxyForwardingFunction{i}",
        f"NdrProxyForwardingFunction{i}",
        "    ldr     x0, [x0, #0x20]",
        "    ldr     x16, [x0]",
        f"    mov     x17, #{i}",
        "    ldr     x16, [x16, x17, LSL #3]",
        "    br      x16",
    ]
lines += ["    END"]
with open(out, "w", newline="\r\n") as f:
    f.write("\n".join(lines) + "\n")
