/*
 * PROJECT:         ReactOS HAL
 * LICENSE:         BSD - See COPYING.ARM in the top level directory
 * FILE:            hal/halx86/legacy/halpnpdd.c
 * PURPOSE:         HAL Plug and Play Device Driver
 * PROGRAMMERS:     ReactOS Portable Systems Group
 */

/* INCLUDES *******************************************************************/

#include <hal.h>

#include <initguid.h>
#include <wdmguid.h>

#ifdef HAL_PIR_EXTENSIONS
#include "pciirq/pciirq.h"
#endif


#define NDEBUG
#include <debug.h>

typedef enum _EXTENSION_TYPE
{
    PdoExtensionType = 0xC0,
    FdoExtensionType
} EXTENSION_TYPE;

typedef enum _PDO_TYPE
{
    AcpiPdo = 0x80,
    WdPdo
} PDO_TYPE;

typedef struct _FDO_EXTENSION
{
    EXTENSION_TYPE ExtensionType;
    struct _PDO_EXTENSION* ChildPdoList;
    PDEVICE_OBJECT PhysicalDeviceObject;
    PDEVICE_OBJECT FunctionalDeviceObject;
    PDEVICE_OBJECT AttachedDeviceObject;
} FDO_EXTENSION, *PFDO_EXTENSION;

typedef struct _PDO_EXTENSION
{
    EXTENSION_TYPE ExtensionType;
    struct _PDO_EXTENSION* Next;
    PDEVICE_OBJECT PhysicalDeviceObject;
    PFDO_EXTENSION ParentFdoExtension;
    PDO_TYPE PdoType;
    PDESCRIPTION_HEADER WdTable;
    LONG InterfaceReferenceCount;
} PDO_EXTENSION, *PPDO_EXTENSION;

/* GLOBALS ********************************************************************/

PDRIVER_OBJECT HalpDriverObject;

/* PRIVATE FUNCTIONS **********************************************************/

NTSTATUS
NTAPI
HalpAddDevice(IN PDRIVER_OBJECT DriverObject,
              IN PDEVICE_OBJECT TargetDevice)
{
    NTSTATUS Status;
    PFDO_EXTENSION FdoExtension;
    PPDO_EXTENSION PdoExtension;
    PDEVICE_OBJECT DeviceObject, AttachedDevice;
    PDEVICE_OBJECT PdoDeviceObject;
//    PDESCRIPTION_HEADER Wdrt;

    DPRINT("HAL: PnP Driver ADD!\n");

    /* Create the FDO */
    Status = IoCreateDevice(DriverObject,
                            sizeof(FDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            0,
                            FALSE,
                            &DeviceObject);
    if (!NT_SUCCESS(Status))
    {
        /* Should not happen */
        DbgBreakPoint();
        return Status;
    }

    /* Setup the FDO extension */
    FdoExtension = DeviceObject->DeviceExtension;
    FdoExtension->ExtensionType = FdoExtensionType;
    FdoExtension->PhysicalDeviceObject = TargetDevice;
    FdoExtension->FunctionalDeviceObject = DeviceObject;
    FdoExtension->ChildPdoList = NULL;

    /* FDO is done initializing */
    DeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;

    /* Attach to the physical device object (the bus) */
    AttachedDevice = IoAttachDeviceToDeviceStack(DeviceObject, TargetDevice);
    if (!AttachedDevice)
    {
        /* Failed, undo everything */
        IoDeleteDevice(DeviceObject);
        return STATUS_NO_SUCH_DEVICE;
    }

    /* Save the attachment */
    FdoExtension->AttachedDeviceObject = AttachedDevice;

    /* Create the PDO */
    Status = IoCreateDevice(DriverObject,
                            sizeof(PDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &PdoDeviceObject);
    if (!NT_SUCCESS(Status))
    {
        /* Fail */
        DPRINT1("HAL: Could not create ACPI device object status=0x%08x\n", Status);
        return Status;
    }

    /* Setup the PDO device extension */
    PdoExtension = PdoDeviceObject->DeviceExtension;
    PdoExtension->ExtensionType = PdoExtensionType;
    PdoExtension->PhysicalDeviceObject = PdoDeviceObject;
    PdoExtension->ParentFdoExtension = FdoExtension;
    PdoExtension->PdoType = AcpiPdo;

    /* Add the PDO to the head of the list */
    PdoExtension->Next = FdoExtension->ChildPdoList;
    FdoExtension->ChildPdoList = PdoExtension;

    /* Initialization is finished */
    PdoDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;

    /* Return status */
    DPRINT("Device added %lx\n", Status);
    return Status;
}

/*
 * The root PCI bus PDO hands these interfaces to the PCI bus driver (and to
 * legacy children). The interface context is the PDO itself, whose reference
 * count keeps it alive for as long as the interface is held.
 */

static
VOID
NTAPI
HalpPnpInterfaceReference(IN PVOID Context)
{
    PPDO_EXTENSION PdoExtension = ((PDEVICE_OBJECT)Context)->DeviceExtension;
    InterlockedIncrement(&PdoExtension->InterfaceReferenceCount);
}

static
VOID
NTAPI
HalpPnpInterfaceDereference(IN PVOID Context)
{
    PPDO_EXTENSION PdoExtension = ((PDEVICE_OBJECT)Context)->DeviceExtension;
    InterlockedDecrement(&PdoExtension->InterfaceReferenceCount);
}

/*
 * RootBusCapability entry point of the version-2 PCI bus interface.  This HAL
 * enumerates a legacy PC-AT PCI host bridge: conventional PCI only (no PCI-X
 * or PCI Express), and no ACPI _OSC feature/control negotiation.  Report that
 * so a Win8+ PCI driver takes the conventional-bus path and does not attempt
 * to build a PCI Express root-complex hierarchy.
 */
static
VOID
NTAPI
HalpPciRootBusCapability(IN PVOID Context,
                         OUT PPCI_ROOT_BUS_HARDWARE_CAPABILITY Capability)
{
    UNREFERENCED_PARAMETER(Context);

    RtlZeroMemory(Capability, sizeof(*Capability));
    Capability->SecondaryInterface = PciConventional;
    /* BusCapabilitiesFound / OscFeatureSupport left zeroed: none present. */
}

/* ExpressWakeControl entry point: no PCI Express, so wake control is a no-op. */
static
VOID
NTAPI
HalpPciExpressWakeControl(IN PVOID Context,
                          IN BOOLEAN EnableWake)
{
    UNREFERENCED_PARAMETER(Context);
    UNREFERENCED_PARAMETER(EnableWake);
}

static
BOOLEAN
NTAPI
HalpPnpTranslateBusAddress(IN PVOID Context,
                           IN PHYSICAL_ADDRESS BusAddress,
                           IN ULONG Length,
                           IN OUT PULONG AddressSpace,
                           OUT PPHYSICAL_ADDRESS TranslatedAddress)
{
    PBUS_HANDLER BusHandler;

    UNREFERENCED_PARAMETER(Context);
    UNREFERENCED_PARAMETER(Length);

    /*
     * Translate through the root PCI bus handler directly. We intentionally do
     * not call the public HalTranslateBusAddress(): for PCIBus it routes through
     * the (possibly hooked) PCI translation pointer and would bounce back into
     * the PCI driver, whereas the caller asked us for the raw HAL translation.
     */
    BusHandler = HalHandlerForBus(PCIBus, 0);
    if (!BusHandler || !BusHandler->TranslateBusAddress) return FALSE;

    return BusHandler->TranslateBusAddress(BusHandler,
                                           BusHandler,
                                           BusAddress,
                                           AddressSpace,
                                           TranslatedAddress);
}

static
PDMA_ADAPTER
NTAPI
HalpPnpGetDmaAdapter(IN PVOID Context,
                     IN PDEVICE_DESCRIPTION DeviceDescription,
                     OUT PULONG NumberOfMapRegisters)
{
    /* Pin the request to our root PCI bus, then let the HAL build the adapter */
    DeviceDescription->BusNumber = 0;
    return HalpGetDmaAdapter(Context, DeviceDescription, NumberOfMapRegisters);
}

NTSTATUS
NTAPI
HalpQueryInterface(IN PDEVICE_OBJECT DeviceObject,
                   IN CONST GUID* InterfaceType,
                   IN USHORT Version,
                   IN PVOID InterfaceSpecificData,
                   IN ULONG InterfaceBufferSize,
                   IN PINTERFACE Interface,
                   OUT PULONG Length)
{
    PPDO_EXTENSION PdoExtension = DeviceObject->DeviceExtension;

    UNREFERENCED_PARAMETER(Version);

    /*
     * The PCI interrupt arbiter is published on the root FDO, not on a PDO. The
     * PnP manager queries it for CmResourceTypeInterrupt while arbitrating the
     * interrupts of the PCI devices enumerated beneath us, and it is driven by
     * the legacy $PIR routing engine, so it is only offered once that engine is
     * up. Without the engine the root FDO has no interface of its own.
     */
    if (((PFDO_EXTENSION)DeviceObject->DeviceExtension)->ExtensionType == FdoExtensionType)
    {
#if defined(HAL_PIR_EXTENSIONS) && !defined(SARCH_XBOX) && !defined(SARCH_PC98)
        NTSTATUS Status;

        if (((CM_RESOURCE_TYPE)(ULONG_PTR)InterfaceSpecificData != CmResourceTypeInterrupt) ||
            !HalpPirEnabled() ||
            !IsEqualIID(InterfaceType, &GUID_ARBITER_INTERFACE_STANDARD))
        {
            return STATUS_NOT_SUPPORTED;
        }

        Status = HalpPirCreateArbiter(DeviceObject);
        if (NT_SUCCESS(Status))
        {
            Status = HalpPirQueryArbiterInterface(Interface, InterfaceBufferSize, Length);
        }
        return Status;
#else
        return STATUS_NOT_SUPPORTED;
#endif
    }

    if (IsEqualIID(InterfaceType, &GUID_BUS_INTERFACE_STANDARD))
    {
        PBUS_INTERFACE_STANDARD BusInterface = (PBUS_INTERFACE_STANDARD)Interface;

        /* Generic bus interface: bus-address translation and DMA adapters */
        *Length = sizeof(BUS_INTERFACE_STANDARD);
        if (InterfaceBufferSize < sizeof(BUS_INTERFACE_STANDARD))
            return STATUS_BUFFER_TOO_SMALL;

        BusInterface->Size = sizeof(BUS_INTERFACE_STANDARD);
        BusInterface->Version = 1;
        BusInterface->Context = DeviceObject;
        BusInterface->InterfaceReference = HalpPnpInterfaceReference;
        BusInterface->InterfaceDereference = HalpPnpInterfaceDereference;
        BusInterface->TranslateBusAddress = HalpPnpTranslateBusAddress;
        BusInterface->GetDmaAdapter = HalpPnpGetDmaAdapter;
        BusInterface->SetBusData = NULL;
        BusInterface->GetBusData = NULL;
    }
    else if ((IsEqualIID(InterfaceType, &GUID_PCI_BUS_INTERFACE_STANDARD) ||
              IsEqualIID(InterfaceType, &GUID_PCI_BUS_INTERFACE_STANDARD2)) &&
             (PdoExtension->PdoType == AcpiPdo))
    {
        PPCI_BUS_INTERFACE_STANDARD PciInterface = (PPCI_BUS_INTERFACE_STANDARD)Interface;
        ULONG MinSize = FIELD_OFFSET(PCI_BUS_INTERFACE_STANDARD, RootBusCapability);
        BOOLEAN Version2 = IsEqualIID(InterfaceType, &GUID_PCI_BUS_INTERFACE_STANDARD2);

        /*
         * PCI configuration-space access interface. We support the classic
         * layout (through LineToPin); a caller whose structure is larger also
         * gets the version-2 direct-call fields. The version-1 GUID leaves
         * those NULL; the version-2 GUID exposes the root-bus capability query
         * and Express wake control (both required by a Win8+ PCI driver).
         */
        if (InterfaceBufferSize < MinSize)
        {
            *Length = MinSize;
            return STATUS_BUFFER_TOO_SMALL;
        }

        PciInterface->Version = Version2 ? 2 : PCI_BUS_INTERFACE_STANDARD_VERSION;
        PciInterface->Context = DeviceObject;
        PciInterface->InterfaceReference = HalpPnpInterfaceReference;
        PciInterface->InterfaceDereference = HalpPnpInterfaceDereference;
        PciInterface->ReadConfig = (PCI_READ_WRITE_CONFIG)HaliPciInterfaceReadConfig;
        PciInterface->WriteConfig = (PCI_READ_WRITE_CONFIG)HaliPciInterfaceWriteConfig;
        PciInterface->PinToLine = NULL;
        PciInterface->LineToPin = NULL;

        if (InterfaceBufferSize >= sizeof(PCI_BUS_INTERFACE_STANDARD))
        {
            PciInterface->RootBusCapability = Version2 ? HalpPciRootBusCapability : NULL;
            PciInterface->ExpressWakeControl = Version2 ? HalpPciExpressWakeControl : NULL;
            PciInterface->Size = sizeof(PCI_BUS_INTERFACE_STANDARD);
            *Length = sizeof(PCI_BUS_INTERFACE_STANDARD);
        }
        else
        {
            PciInterface->Size = (USHORT)MinSize;
            *Length = MinSize;
        }
    }
    else
    {
        /* Not an interface the HAL provides on this device */
        return STATUS_NOT_SUPPORTED;
    }

    /* Keep the PDO referenced for as long as the interface is held */
    InterlockedIncrement(&PdoExtension->InterfaceReferenceCount);
    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
HalpQueryDeviceRelations(IN PDEVICE_OBJECT DeviceObject,
                         IN DEVICE_RELATION_TYPE RelationType,
                         OUT PDEVICE_RELATIONS* DeviceRelations)
{
    EXTENSION_TYPE ExtensionType;
    PPDO_EXTENSION PdoExtension;
    PFDO_EXTENSION FdoExtension;
    PDEVICE_RELATIONS PdoRelations, FdoRelations;
    PDEVICE_OBJECT* ObjectEntry;
    ULONG i = 0, PdoCount = 0;

    /* Get FDO device extension and PDO count */
    FdoExtension = DeviceObject->DeviceExtension;
    ExtensionType = FdoExtension->ExtensionType;

    /* What do they want? */
    if (RelationType == BusRelations)
    {
        /* This better be an FDO */
        if (ExtensionType == FdoExtensionType)
        {
            /* Count how many PDOs we have */
            PdoExtension = FdoExtension->ChildPdoList;
            while (PdoExtension)
            {
                /* Next one */
                PdoExtension = PdoExtension->Next;
                PdoCount++;
            }

            /* Add the PDOs that already exist in the device relations */
            if (*DeviceRelations)
            {
                PdoCount += (*DeviceRelations)->Count;
            }

            /* Allocate our structure */
            FdoRelations = ExAllocatePoolWithTag(PagedPool,
                                                 FIELD_OFFSET(DEVICE_RELATIONS,
                                                              Objects) +
                                                 sizeof(PDEVICE_OBJECT) * PdoCount,
                                                 TAG_HAL);
            if (!FdoRelations) return STATUS_INSUFFICIENT_RESOURCES;

            /* Save our count */
            FdoRelations->Count = PdoCount;

            /* Query existing relations */
            ObjectEntry = FdoRelations->Objects;
            if (*DeviceRelations)
            {
                /* Check if there were any */
                if ((*DeviceRelations)->Count)
                {
                    /* Loop them all */
                    do
                    {
                        /* Copy into our structure */
                        *ObjectEntry++ = (*DeviceRelations)->Objects[i];
                    }
                    while (++i < (*DeviceRelations)->Count);
                }

                /* Free existing structure */
                ExFreePool(*DeviceRelations);
            }

            /* Now check if we have a PDO list */
            PdoExtension = FdoExtension->ChildPdoList;
            if (PdoExtension)
            {
                /* Loop the PDOs */
                do
                {
                    /* Save our own PDO and reference it */
                    *ObjectEntry++ = PdoExtension->PhysicalDeviceObject;
                    ObReferenceObject(PdoExtension->PhysicalDeviceObject);

                    /* Go to our next PDO */
                    PdoExtension = PdoExtension->Next;
                }
                while (PdoExtension);
            }

            /* Return the new structure */
            *DeviceRelations = FdoRelations;
            return STATUS_SUCCESS;
        }
    }
    else
    {
        /* The only other thing we support is a target relation for the PDO */
        if ((RelationType == TargetDeviceRelation) &&
            (ExtensionType == PdoExtensionType))
        {
            /* Only one entry */
            PdoRelations = ExAllocatePoolWithTag(PagedPool,
                                                 sizeof(DEVICE_RELATIONS),
                                                 TAG_HAL);
            if (!PdoRelations) return STATUS_INSUFFICIENT_RESOURCES;

            /* Fill it out and reference us */
            PdoRelations->Count = 1;
            PdoRelations->Objects[0] = DeviceObject;
            ObReferenceObject(DeviceObject);

            /* Return it */
            *DeviceRelations = PdoRelations;
            return STATUS_SUCCESS;
        }
    }

    /* We don't support anything else */
    return STATUS_NOT_SUPPORTED;
}

NTSTATUS
NTAPI
HalpQueryCapabilities(IN PDEVICE_OBJECT DeviceObject,
                      OUT PDEVICE_CAPABILITIES Capabilities)
{
    //PPDO_EXTENSION PdoExtension;
    NTSTATUS Status;
    PAGED_CODE();

    /* Get the extension and check for valid version */
    //PdoExtension = DeviceObject->DeviceExtension;
    ASSERT(Capabilities->Version == 1);
    if (Capabilities->Version == 1)
    {
        /* Can't lock or eject us */
        Capabilities->LockSupported = FALSE;
        Capabilities->EjectSupported = FALSE;

        /* Can't remove or dock us */
        Capabilities->Removable = FALSE;
        Capabilities->DockDevice = FALSE;

        /* Can't access us raw */
        Capabilities->RawDeviceOK = FALSE;

        /* We have a unique ID, and don't bother the user */
        Capabilities->UniqueID = TRUE;
        Capabilities->SilentInstall = TRUE;

        /* Fill out the address */
        Capabilities->Address = InterfaceTypeUndefined;
        Capabilities->UINumber = InterfaceTypeUndefined;

        /* Fill out latencies */
        Capabilities->D1Latency = 0;
        Capabilities->D2Latency = 0;
        Capabilities->D3Latency = 0;

        /* Fill out supported device states */
        Capabilities->DeviceState[PowerSystemWorking] = PowerDeviceD0;
        Capabilities->DeviceState[PowerSystemHibernate] = PowerDeviceD3;
        Capabilities->DeviceState[PowerSystemShutdown] = PowerDeviceD3;
        Capabilities->DeviceState[PowerSystemSleeping3] = PowerDeviceD3;

        /* Done */
        Status = STATUS_SUCCESS;
    }
    else
    {
        /* Fail */
        Status = STATUS_NOT_SUPPORTED;
    }

    /* Return status */
    return Status;
}

/*
 * Return the first byte above all physical RAM, rounded up to a 1 MB boundary,
 * or 0 if it cannot be determined.  The root PCI memory window handed to the PCI
 * driver must not overlap RAM: the driver's memory arbiter is bounded only by
 * this window (it is NOT seeded with the system RAM map the way the kernel's own
 * root arbiters are), so if the window covers RAM the arbiter can place a device
 * BAR on top of RAM.  The device then decodes over RAM and silently displays/does
 * nothing - a black screen with no error, because arbitration "succeeded".
 */
static
ULONGLONG
HalpHighestRamAddress(VOID)
{
    PPHYSICAL_MEMORY_RANGE Ranges, Entry;
    ULONGLONG Top = 0, End;

    Ranges = MmGetPhysicalMemoryRanges();
    if (!Ranges) return 0;

    for (Entry = Ranges;
         (Entry->BaseAddress.QuadPart != 0) || (Entry->NumberOfBytes.QuadPart != 0);
         Entry++)
    {
        End = (ULONGLONG)Entry->BaseAddress.QuadPart + (ULONGLONG)Entry->NumberOfBytes.QuadPart;
        if (End > Top) Top = End;
    }

    ExFreePool(Ranges);

    /* Round up to a 1 MB boundary - PCI memory holes are MB-aligned. */
    return (Top + 0xFFFFFULL) & ~0xFFFFFULL;
}

/* Append one CmResourceTypeMemory descriptor for [Base, Limit] (inclusive). */
static
VOID
HalpAddMemoryDescriptor(
    IN OUT PCM_PARTIAL_RESOURCE_DESCRIPTOR *Descriptor,
    IN ULONGLONG Base,
    IN ULONGLONG Limit)
{
    ULONGLONG Length = Limit - Base + 1;

    /* A full 32-bit window's inclusive length overflows the ULONG field. */
    if (Length > MAXULONG) Length = MAXULONG;

    (*Descriptor)->Type = CmResourceTypeMemory;
    (*Descriptor)->ShareDisposition = CmResourceShareShared;
    (*Descriptor)->Flags = CM_RESOURCE_MEMORY_READ_WRITE;
    (*Descriptor)->u.Memory.Start.QuadPart = (LONGLONG)Base;
    (*Descriptor)->u.Memory.Length = (ULONG)Length;
    (*Descriptor)++;
}

/*
 * Emit the PCI-decodable sub-ranges of memory window [Base, Limit]: the legacy
 * compatibility hole [0xA0000, 0xFFFFF] (VGA aperture + option ROMs) and
 * everything at or above the top of RAM (RamTop) - skipping the RAM regions in
 * between so the PCI driver never allocates a BAR over RAM.  With Descriptor ==
 * NULL it only counts.  Returns the number of descriptors produced.  If RamTop
 * is 0 (unknown) it reports the whole window, the pre-existing behavior.
 */
static
ULONG
HalpReportPciMemoryWindow(
    IN ULONGLONG Base,
    IN ULONGLONG Limit,
    IN ULONGLONG RamTop,
    IN OUT PCM_PARTIAL_RESOURCE_DESCRIPTOR *Descriptor OPTIONAL)
{
    ULONG Count = 0;
    ULONGLONG SubBase, SubLimit;

    if (RamTop == 0)
    {
        /* RAM extent unknown - report the window as-is (length capped downstream). */
        if (Descriptor) HalpAddMemoryDescriptor(Descriptor, Base, Limit);
        return 1;
    }

    /* Legacy compatibility region [0xA0000, 0xFFFFF]. */
    SubBase = (Base > 0xA0000ULL) ? Base : 0xA0000ULL;
    SubLimit = (Limit < 0xFFFFFULL) ? Limit : 0xFFFFFULL;
    if (SubBase <= SubLimit)
    {
        if (Descriptor) HalpAddMemoryDescriptor(Descriptor, SubBase, SubLimit);
        Count++;
    }

    /* High MMIO hole: everything at or above the top of RAM. */
    if ((RamTop < 0xFFFFFFFFULL) && (Limit >= RamTop))
    {
        SubBase = (Base > RamTop) ? Base : RamTop;
        SubLimit = Limit;
        if (Descriptor) HalpAddMemoryDescriptor(Descriptor, SubBase, SubLimit);
        Count++;
    }

    return Count;
}

NTSTATUS
NTAPI
HalpQueryResources(IN PDEVICE_OBJECT DeviceObject,
                   OUT PCM_RESOURCE_LIST *Resources)
{
    PPDO_EXTENSION DeviceExtension = DeviceObject->DeviceExtension;
    PCM_RESOURCE_LIST ResourceList;
    PCM_PARTIAL_RESOURCE_DESCRIPTOR Descriptor;
    PBUS_HANDLER BusHandler;
    PSUPPORTED_RANGE Range;
    ULONGLONG RangeLength;
    ULONGLONG RamTop;
    ULONG Count, Size;
    PAGED_CODE();

    /* The root PCI bus PDO tells the PCI driver which resources it owns */
    if (DeviceExtension->PdoType == AcpiPdo)
    {
        /* Grab the root PCI bus handler so we can report its decode windows */
        BusHandler = HalHandlerForBus(PCIBus, 0);

        /* Learn where RAM ends so we never report it as a PCI memory window */
        RamTop = HalpHighestRamAddress();

        /* Always one descriptor for the bus-number range this root heads... */
        Count = 1;

        /* ...plus one per non-empty I/O window and per PCI memory sub-window */
        if (BusHandler && BusHandler->BusAddresses)
        {
            for (Range = &BusHandler->BusAddresses->IO; Range; Range = Range->Next)
            {
                if (Range->Limit) Count++;
            }
            for (Range = &BusHandler->BusAddresses->Memory; Range; Range = Range->Next)
            {
                if (Range->Limit)
                    Count += HalpReportPciMemoryWindow(Range->Base, Range->Limit, RamTop, NULL);
            }
        }

        /* Allocate a resource list big enough for all of the descriptors */
        Size = sizeof(CM_RESOURCE_LIST) +
               (Count - 1) * sizeof(CM_PARTIAL_RESOURCE_DESCRIPTOR);
        ResourceList = ExAllocatePoolWithTag(PagedPool, Size, TAG_HAL);
        if (!ResourceList) return STATUS_INSUFFICIENT_RESOURCES;

        /* Initialize the list header */
        RtlZeroMemory(ResourceList, Size);
        ResourceList->Count = 1;
        ResourceList->List[0].BusNumber = 0;
        ResourceList->List[0].InterfaceType = PCIBus;
        ResourceList->List[0].PartialResourceList.Version = 1;
        ResourceList->List[0].PartialResourceList.Revision = 1;
        ResourceList->List[0].PartialResourceList.Count = Count;

        Descriptor = ResourceList->List[0].PartialResourceList.PartialDescriptors;

        /* Report the range of PCI bus numbers this root owns */
        Descriptor->Type = CmResourceTypeBusNumber;
        Descriptor->ShareDisposition = CmResourceShareShared;
        Descriptor->u.BusNumber.Start = 0;
        Descriptor->u.BusNumber.Length = HalpMaxPciBus + 1;
        Descriptor++;

        /* Report the I/O and memory windows the root bus decodes */
        if (BusHandler && BusHandler->BusAddresses)
        {
            for (Range = &BusHandler->BusAddresses->IO; Range; Range = Range->Next)
            {
                if (!Range->Limit) continue;

                /*
                 * The inclusive length Limit-Base+1 is 2^32 for a full 32-bit
                 * window, which does not fit the descriptor's ULONG Length.
                 * Cap it to MAXULONG so the window is still reported (as
                 * [Base, Base+MAXULONG-1]) rather than dropped - otherwise the
                 * PCI driver's arbiter is started with no window and can place
                 * nothing.
                 */
                RangeLength = (ULONGLONG)Range->Limit - Range->Base + 1;
                if (RangeLength > MAXULONG) RangeLength = MAXULONG;

                Descriptor->Type = CmResourceTypePort;
                Descriptor->ShareDisposition = CmResourceShareShared;
                Descriptor->Flags = CM_RESOURCE_PORT_IO;
                Descriptor->u.Port.Start.QuadPart = Range->Base;
                Descriptor->u.Port.Length = (ULONG)RangeLength;
                Descriptor++;
            }
            for (Range = &BusHandler->BusAddresses->Memory; Range; Range = Range->Next)
            {
                if (!Range->Limit) continue;

                /*
                 * Report the PCI-decodable sub-ranges of this window, carving out
                 * the RAM regions so the PCI driver's arbiter cannot place a BAR
                 * over RAM (which decodes nothing -> silent black screen).
                 */
                HalpReportPciMemoryWindow(Range->Base, Range->Limit, RamTop, &Descriptor);
            }
        }

        /* Return resources and success */
        *Resources = ResourceList;
        return STATUS_SUCCESS;
    }
    else if (DeviceExtension->PdoType == WdPdo)
    {
        /* Watchdog doesn't */
        return STATUS_NOT_SUPPORTED;
    }
    else
    {
        /* This shouldn't happen */
        return STATUS_UNSUCCESSFUL;
    }
}

NTSTATUS
NTAPI
HalpQueryResourceRequirements(IN PDEVICE_OBJECT DeviceObject,
                              OUT PIO_RESOURCE_REQUIREMENTS_LIST *Requirements)
{
    PPDO_EXTENSION DeviceExtension = DeviceObject->DeviceExtension;
    PAGED_CODE();

    /* Only the ACPI PDO has requirements */
    if (DeviceExtension->PdoType == AcpiPdo)
    {
        /* Query ACPI requirements */
//        return HalpQueryAcpiResourceRequirements(Requirements);
        return STATUS_SUCCESS;
    }
    else if (DeviceExtension->PdoType == WdPdo)
    {
        /* Watchdog doesn't */
        return STATUS_NOT_SUPPORTED;
    }
    else
    {
        /* This shouldn't happen */
        return STATUS_UNSUCCESSFUL;
    }
}

NTSTATUS
NTAPI
HalpQueryIdPdo(IN PDEVICE_OBJECT DeviceObject,
               IN BUS_QUERY_ID_TYPE IdType,
               OUT PUSHORT *BusQueryId)
{
    PPDO_EXTENSION PdoExtension;
    PDO_TYPE PdoType;
    PWCHAR CurrentId;
    WCHAR Id[100];
    NTSTATUS Status;
    ULONG Length = 0;
    PWCHAR Buffer;

    /* Get the PDO type */
    PdoExtension = DeviceObject->DeviceExtension;
    PdoType = PdoExtension->PdoType;

    /* What kind of ID is being requested? */
    DPRINT("ID: %d\n", IdType);
    switch (IdType)
    {
        case BusQueryDeviceID:
        case BusQueryHardwareIDs:

            /* What kind of PDO is this? */
            if (PdoType == AcpiPdo)
            {
                /* ACPI ID */
                CurrentId = L"PCI_HAL\\PNP0A03";
                RtlCopyMemory(Id, CurrentId, (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL));
                Length += (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);

                CurrentId = L"*PNP0A03";
                RtlCopyMemory(&Id[wcslen(Id) + 1], CurrentId, (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL));
                Length += (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);
            }
#if 0
            else if (PdoType == WdPdo)
            {
                /* WatchDog ID */
                CurrentId = L"ACPI_HAL\\PNP0C18";
                RtlCopyMemory(Id, CurrentId, (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL));
                Length += (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);

                CurrentId = L"*PNP0C18";
                RtlCopyMemory(&Id[wcslen(Id) + 1], CurrentId, (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL));
                Length += (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);
            }
#endif
            else
            {
                /* Unknown */
                return STATUS_NOT_SUPPORTED;
            }
            break;

        case BusQueryInstanceID:

            /* Instance ID */
            CurrentId = L"0";
            RtlCopyMemory(Id, CurrentId, (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL));
            Length += (wcslen(CurrentId) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);
            break;

        case BusQueryCompatibleIDs:
        default:

            /* We don't support anything else */
            return STATUS_NOT_SUPPORTED;
    }

    /* Allocate the buffer */
    Buffer = ExAllocatePoolWithTag(PagedPool,
                                   Length + sizeof(UNICODE_NULL),
                                   TAG_HAL);
    if (Buffer)
    {
        /* Copy the string and null-terminate it */
        RtlCopyMemory(Buffer, Id, Length);
        Buffer[Length / sizeof(WCHAR)] = UNICODE_NULL;

        /* Return string */
        *BusQueryId = Buffer;
        Status = STATUS_SUCCESS;
        DPRINT("Returning: %S\n", *BusQueryId);
    }
    else
    {
        /* Fail */
        Status = STATUS_INSUFFICIENT_RESOURCES;
    }

    /* Return status */
    return Status;
}

NTSTATUS
NTAPI
HalpQueryIdFdo(IN PDEVICE_OBJECT DeviceObject,
               IN BUS_QUERY_ID_TYPE IdType,
               OUT PUSHORT *BusQueryId)
{
    NTSTATUS Status;
    ULONG Length;
    PWCHAR Id;
    PWCHAR Buffer;

    /* What kind of ID is being requested? */
    DPRINT("ID: %d\n", IdType);
    switch (IdType)
    {
        case BusQueryDeviceID:
        case BusQueryHardwareIDs:

            /* This is our hardware ID */
            Id = HalHardwareIdString;
            break;

        case BusQueryInstanceID:

            /* And our instance ID */
            Id = L"0";
            break;

        default:

            /* We don't support anything else */
            return STATUS_NOT_SUPPORTED;
    }

    /* Calculate the length */
    Length = (wcslen(Id) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);

    /* Allocate the buffer */
    Buffer = ExAllocatePoolWithTag(PagedPool,
                                   Length + sizeof(UNICODE_NULL),
                                   TAG_HAL);
    if (Buffer)
    {
        /* Copy the string and null-terminate it */
        RtlCopyMemory(Buffer, Id, Length);
        Buffer[Length / sizeof(WCHAR)] = UNICODE_NULL;

        /* Return string */
        *BusQueryId = Buffer;
        Status = STATUS_SUCCESS;
        DPRINT("Returning: %S\n", *BusQueryId);
    }
    else
    {
        /* Fail */
        Status = STATUS_INSUFFICIENT_RESOURCES;
    }

    /* Return status */
    return Status;
}

NTSTATUS
NTAPI
HalpDispatchPnp(IN PDEVICE_OBJECT DeviceObject,
                IN PIRP Irp)
{
    PIO_STACK_LOCATION IoStackLocation;
    //PPDO_EXTENSION PdoExtension;
    PFDO_EXTENSION FdoExtension;
    NTSTATUS Status;
    UCHAR Minor;

    /* Get the device extension and stack location */
    FdoExtension = DeviceObject->DeviceExtension;
    IoStackLocation = IoGetCurrentIrpStackLocation(Irp);
    Minor = IoStackLocation->MinorFunction;

    /* FDO? */
    if (FdoExtension->ExtensionType == FdoExtensionType)
    {
        /* Query the IRP type */
        switch (Minor)
        {
            case IRP_MN_QUERY_DEVICE_RELATIONS:

                /* Call the worker */
                DPRINT("Querying device relations for FDO\n");
                Status = HalpQueryDeviceRelations(DeviceObject,
                                                  IoStackLocation->Parameters.QueryDeviceRelations.Type,
                                                  (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_INTERFACE:

                /* Call the worker */
                DPRINT("Querying interface for FDO\n");
                Status = HalpQueryInterface(DeviceObject,
                                            IoStackLocation->Parameters.QueryInterface.InterfaceType,
                                            IoStackLocation->Parameters.QueryInterface.Version,
                                            IoStackLocation->Parameters.QueryInterface.InterfaceSpecificData,
                                            IoStackLocation->Parameters.QueryInterface.Size,
                                            IoStackLocation->Parameters.QueryInterface.Interface,
                                            (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_ID:

                /* Call the worker */
                DPRINT("Querying ID for FDO\n");
                Status = HalpQueryIdFdo(DeviceObject,
                                        IoStackLocation->Parameters.QueryId.IdType,
                                        (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_CAPABILITIES:

                /* Call the worker */
                DPRINT("Querying the capabilities for the FDO\n");
                Status = HalpQueryCapabilities(DeviceObject,
                                               IoStackLocation->Parameters.DeviceCapabilities.Capabilities);
                break;

            default:

                DPRINT("Other IRP: %lx\n", Minor);
                Status = STATUS_NOT_SUPPORTED;
                break;
        }

        /* What happpened? */
        if ((NT_SUCCESS(Status)) || (Status == STATUS_NOT_SUPPORTED))
        {
            /* Set the IRP status, unless this isn't understood */
            if (Status != STATUS_NOT_SUPPORTED)
            {
                Irp->IoStatus.Status = Status;
            }

            /* Pass it on */
            IoSkipCurrentIrpStackLocation(Irp);
            return IoCallDriver(FdoExtension->AttachedDeviceObject, Irp);
        }

        /* Otherwise, we failed, so set the status and complete the request */
        DPRINT1("IRP failed with status: %lx\n", Status);
        Irp->IoStatus.Status = Status;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return Status;
    }
    else
    {
        /* This is a PDO instead */
        ASSERT(FdoExtension->ExtensionType == PdoExtensionType);
        //PdoExtension = (PPDO_EXTENSION)FdoExtension;

        /* Query the IRP type */
        Status = STATUS_SUCCESS;
        switch (Minor)
        {
            case IRP_MN_START_DEVICE:

                /*
                 * The PCI bus driver is now running on top of this root PDO,
                 * which is the point at which its interrupt-routing interface
                 * can be obtained and legacy PCI IRQ routing brought up. It is
                 * a no-op when the driver offers no such interface.
                 */
                DPRINT("Start device received\n");
#if defined(HAL_PIR_EXTENSIONS) && !defined(SARCH_XBOX) && !defined(SARCH_PC98)
                HalpPirActivate(DeviceObject);
#endif
                break;

            case IRP_MN_REMOVE_DEVICE:

                /* Check if this is a PCI device */
                DPRINT("Remove device received\n");

                /* We're done */
                Status = STATUS_SUCCESS;
                break;

            case IRP_MN_SURPRISE_REMOVAL:

                /* Inherit whatever status we had */
                DPRINT("Surprise removal IRP\n");
                Status = Irp->IoStatus.Status;
                break;

            case IRP_MN_QUERY_DEVICE_RELATIONS:

                /* Query the device relations */
                DPRINT("Querying PDO relations\n");
                Status = HalpQueryDeviceRelations(DeviceObject,
                                                  IoStackLocation->Parameters.QueryDeviceRelations.Type,
                                                  (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_INTERFACE:

                /* Call the worker */
                DPRINT("Querying interface for PDO\n");
                Status = HalpQueryInterface(DeviceObject,
                                            IoStackLocation->Parameters.QueryInterface.InterfaceType,
                                            IoStackLocation->Parameters.QueryInterface.Version,
                                            IoStackLocation->Parameters.QueryInterface.InterfaceSpecificData,
                                            IoStackLocation->Parameters.QueryInterface.Size,
                                            IoStackLocation->Parameters.QueryInterface.Interface,
                                            (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_CAPABILITIES:

                /* Call the worker */
                DPRINT("Querying the capabilities for the PDO\n");
                Status = HalpQueryCapabilities(DeviceObject,
                                               IoStackLocation->Parameters.DeviceCapabilities.Capabilities);
                break;

            case IRP_MN_QUERY_RESOURCES:

                /* Call the worker */
                DPRINT("Querying the resources for the PDO\n");
                Status = HalpQueryResources(DeviceObject, (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_RESOURCE_REQUIREMENTS:

                /* Call the worker */
                DPRINT("Querying the resource requirements for the PDO\n");
                Status = HalpQueryResourceRequirements(DeviceObject,
                                                       (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_ID:

                /* Call the worker */
                DPRINT("Query the ID for the PDO\n");
                Status = HalpQueryIdPdo(DeviceObject,
                                        IoStackLocation->Parameters.QueryId.IdType,
                                        (PVOID)&Irp->IoStatus.Information);
                break;

            case IRP_MN_QUERY_DEVICE_TEXT:

                /* Inherit whatever status we had */
                DPRINT("Query text for the PDO\n");
                Status = Irp->IoStatus.Status;
                break;

            case IRP_MN_FILTER_RESOURCE_REQUIREMENTS:

                /* Inherit whatever status we had */
                DPRINT("Filter resource requirements for the PDO\n");
                Status = Irp->IoStatus.Status;
                break;

            case IRP_MN_QUERY_PNP_DEVICE_STATE:

                /* Inherit whatever status we had */
                DPRINT("Query device state for the PDO\n");
                Status = Irp->IoStatus.Status;
                break;

            case IRP_MN_QUERY_BUS_INFORMATION:

                /* Inherit whatever status we had */
                DPRINT("Query bus information for the PDO\n");
                Status = Irp->IoStatus.Status;
                break;

            default:

                /* We don't handle anything else, so inherit the old state */
                DPRINT1("Illegal IRP: %lx\n", Minor);
                Status = Irp->IoStatus.Status;
                break;
        }

        /* If it's not supported, inherit the old status */
        if (Status == STATUS_NOT_SUPPORTED) Status = Irp->IoStatus.Status;

        /* Complete the IRP */
        DPRINT("IRP completed with status: %lx\n", Status);
        Irp->IoStatus.Status = Status;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return Status;
    }
}

NTSTATUS
NTAPI
HalpDispatchWmi(IN PDEVICE_OBJECT DeviceObject,
                IN PIRP Irp)
{
    UNIMPLEMENTED_DBGBREAK("HAL: PnP Driver WMI!\n");
    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
HalpDispatchPower(IN PDEVICE_OBJECT DeviceObject,
                  IN PIRP Irp)
{
    PFDO_EXTENSION FdoExtension;

    DPRINT1("HAL: PnP Driver Power!\n");
    FdoExtension = DeviceObject->DeviceExtension;
    if (FdoExtension->ExtensionType == FdoExtensionType)
    {
        PoStartNextPowerIrp(Irp);
        IoSkipCurrentIrpStackLocation(Irp);
        return PoCallDriver(FdoExtension->AttachedDeviceObject, Irp);
    }
    else
    {
        PoStartNextPowerIrp(Irp);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_SUCCESS;
    }
}

NTSTATUS
NTAPI
HalpDriverEntry(IN PDRIVER_OBJECT DriverObject,
                IN PUNICODE_STRING RegistryPath)
{
    NTSTATUS Status;
    PDEVICE_OBJECT TargetDevice = NULL;

    DPRINT("HAL: PnP Driver ENTRY!\n");

    /* This is us */
    HalpDriverObject = DriverObject;

    /* Set up add device */
    DriverObject->DriverExtension->AddDevice = HalpAddDevice;

    /* Set up the callouts */
    DriverObject->MajorFunction[IRP_MJ_PNP] = HalpDispatchPnp;
    DriverObject->MajorFunction[IRP_MJ_POWER] = HalpDispatchPower;
    DriverObject->MajorFunction[IRP_MJ_SYSTEM_CONTROL] = HalpDispatchWmi;

    /* Create the PDO and tell the PnP manager about us*/
    Status = IoReportDetectedDevice(DriverObject,
                                    InterfaceTypeUndefined,
                                    -1,
                                    -1,
                                    NULL,
                                    NULL,
                                    FALSE,
                                    &TargetDevice);
    if (!NT_SUCCESS(Status))
        return Status;

    TargetDevice->Flags &= ~DO_DEVICE_INITIALIZING;

    /* Set up the device stack */
    Status = HalpAddDevice(DriverObject, TargetDevice);
    if (!NT_SUCCESS(Status))
    {
        IoDeleteDevice(TargetDevice);
        return Status;
    }

    /* Return to kernel */
    return Status;
}

NTSTATUS
NTAPI
HaliInitPnpDriver(VOID)
{
    NTSTATUS Status;
    UNICODE_STRING DriverString;
    PAGED_CODE();

    /* Create the driver */
    RtlInitUnicodeString(&DriverString, L"\\Driver\\PCI_HAL");
    Status = IoCreateDriver(&DriverString, HalpDriverEntry);

    /* Return status */
    return Status;
}

/* EOF */
