/*
 * PROJECT:     Kernel Mode Device Framework
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Missing headers (wdfcxbase.h)
 * COPYRIGHT:   Copyright 2026 Justin Miller <justin.miller@reactos.org>
 *
 * The device init surface a class extension uses to run its own PnP, power
 * and power policy callbacks around its client's. Layouts match KMDF 1.31.
 */

#ifndef _WDFCXBASE_H_
#define _WDFCXBASE_H_

#include "wdfcx.h"

/* File create, the one callback in WDFCX_FILEOBJECT_CONFIG */
typedef
_Function_class_(EVT_WDFCX_DEVICE_FILE_CREATE)
_IRQL_requires_same_
BOOLEAN
NTAPI
EVT_WDFCX_DEVICE_FILE_CREATE(
    _In_ WDFDEVICE Device,
    _In_ WDFREQUEST Request,
    _In_opt_ WDFFILEOBJECT FileObject);

/* PnP and power */

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_PREPARE_HARDWARE)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_PREPARE_HARDWARE(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef EVT_WDFCX_DEVICE_PRE_PREPARE_HARDWARE *PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef EVT_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_PREPARE_HARDWARE)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_PREPARE_HARDWARE(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef EVT_WDFCX_DEVICE_POST_PREPARE_HARDWARE *PFN_WDFCX_DEVICE_POST_PREPARE_HARDWARE;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_RELEASE_HARDWARE)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_RELEASE_HARDWARE(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef EVT_WDFCX_DEVICE_PRE_RELEASE_HARDWARE *PFN_WDFCX_DEVICE_PRE_RELEASE_HARDWARE;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_RELEASE_HARDWARE)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_RELEASE_HARDWARE(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef EVT_WDFCX_DEVICE_POST_RELEASE_HARDWARE *PFN_WDFCX_DEVICE_POST_RELEASE_HARDWARE;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_D0_ENTRY)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_D0_ENTRY(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_PRE_D0_ENTRY *PFN_WDFCX_DEVICE_PRE_D0_ENTRY;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_D0_ENTRY)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_D0_ENTRY(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_POST_D0_ENTRY *PFN_WDFCX_DEVICE_POST_D0_ENTRY;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_D0_EXIT)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_D0_EXIT(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState);

typedef EVT_WDFCX_DEVICE_PRE_D0_EXIT *PFN_WDFCX_DEVICE_PRE_D0_EXIT;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_D0_EXIT)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_D0_EXIT(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState);

typedef EVT_WDFCX_DEVICE_POST_D0_EXIT *PFN_WDFCX_DEVICE_POST_D0_EXIT;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL *PFN_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SURPRISE_REMOVAL)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_SURPRISE_REMOVAL(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_SURPRISE_REMOVAL *PFN_WDFCX_DEVICE_POST_SURPRISE_REMOVAL;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState);

typedef EVT_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX *PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState);

typedef EVT_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX *PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED *PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED *PFN_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef EVT_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState);

typedef EVT_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED *PFN_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState);

typedef EVT_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED *PFN_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED;

typedef struct _WDFCX_PNPPOWER_EVENT_CALLBACKS
{
    ULONG Size;
    PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE EvtCxDevicePrePrepareHardware;
    PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP EvtCxDevicePrePrepareHardwareFailedCleanup;
    PFN_WDFCX_DEVICE_POST_PREPARE_HARDWARE EvtCxDevicePostPrepareHardware;
    PFN_WDFCX_DEVICE_PRE_RELEASE_HARDWARE EvtCxDevicePreReleaseHardware;
    PFN_WDFCX_DEVICE_POST_RELEASE_HARDWARE EvtCxDevicePostReleaseHardware;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY EvtCxDevicePreD0Entry;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP EvtCxDevicePreD0EntryFailedCleanup;
    PFN_WDFCX_DEVICE_POST_D0_ENTRY EvtCxDevicePostD0Entry;
    PFN_WDFCX_DEVICE_PRE_D0_EXIT EvtCxDevicePreD0Exit;
    PFN_WDFCX_DEVICE_POST_D0_EXIT EvtCxDevicePostD0Exit;
    PFN_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL EvtCxDevicePreSurpriseRemoval;
    PFN_WDFCX_DEVICE_POST_SURPRISE_REMOVAL EvtCxDevicePostSurpriseRemoval;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT EvtCxDevicePreSelfManagedIoInit;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP EvtCxDevicePreSelfManagedIoInitFailedCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT EvtCxDevicePostSelfManagedIoInit;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART EvtCxDevicePreSelfManagedIoRestart;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP EvtCxDevicePreSelfManagedIoRestartFailedCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART EvtCxDevicePostSelfManagedIoRestart;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND EvtCxDevicePreSelfManagedIoSuspend;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND EvtCxDevicePostSelfManagedIoSuspend;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH EvtCxDevicePreSelfManagedIoFlush;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH EvtCxDevicePostSelfManagedIoFlush;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP EvtCxDevicePreSelfManagedIoCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP EvtCxDevicePostSelfManagedIoCleanup;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX EvtCxDevicePreSelfManagedIoRestartEx;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP EvtCxDevicePreSelfManagedIoRestartExFailedCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX EvtCxDevicePostSelfManagedIoRestartEx;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX EvtCxDevicePreSelfManagedIoSuspendEx;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX EvtCxDevicePostSelfManagedIoSuspendEx;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED EvtCxDevicePreD0EntryPostHardwareEnabled;
    PFN_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED EvtCxDevicePostD0EntryPostHardwareEnabled;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP EvtCxDevicePreD0EntryPostHardwareEnabledFailedCleanup;
    PFN_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED EvtCxDevicePreD0ExitPreHardwareDisabled;
    PFN_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED EvtCxDevicePostD0ExitPreHardwareDisabled;
} WDFCX_PNPPOWER_EVENT_CALLBACKS, *PWDFCX_PNPPOWER_EVENT_CALLBACKS;

FORCEINLINE
VOID
WDFCX_PNPPOWER_EVENT_CALLBACKS_INIT(
    _Out_ PWDFCX_PNPPOWER_EVENT_CALLBACKS Callbacks)
{
    RtlZeroMemory(Callbacks, sizeof(*Callbacks));
    Callbacks->Size = sizeof(*Callbacks);
}

/* Power policy */

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0 *PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0_FAILED_CLEANUP(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_S0)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_S0(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_S0 *PFN_WDFCX_DEVICE_POST_ARM_WAKE_FROM_S0;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_S0)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_S0(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_S0 *PFN_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_S0;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_S0)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_S0(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_S0 *PFN_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_S0;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_WAKE_FROM_S0_TRIGGERED)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_WAKE_FROM_S0_TRIGGERED(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_WAKE_FROM_S0_TRIGGERED *PFN_WDFCX_DEVICE_PRE_WAKE_FROM_S0_TRIGGERED;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_WAKE_FROM_S0_TRIGGERED)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_WAKE_FROM_S0_TRIGGERED(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_WAKE_FROM_S0_TRIGGERED *PFN_WDFCX_DEVICE_POST_WAKE_FROM_S0_TRIGGERED;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX *PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_FAILED_CLEANUP(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX *PFN_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON(
    _In_ WDFDEVICE Device,
    _In_ BOOLEAN DeviceWakeEnabled,
    _In_ BOOLEAN ChildrenArmedForWake);

typedef EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON *PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON_FAILED_CLEANUP)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON_FAILED_CLEANUP(
    _In_ WDFDEVICE Device,
    _In_ BOOLEAN DeviceWakeEnabled,
    _In_ BOOLEAN ChildrenArmedForWake);

typedef EVT_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON_FAILED_CLEANUP *PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON_FAILED_CLEANUP;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX_WITH_REASON)
_IRQL_requires_same_
NTSTATUS
NTAPI
EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX_WITH_REASON(
    _In_ WDFDEVICE Device,
    _In_ BOOLEAN DeviceWakeEnabled,
    _In_ BOOLEAN ChildrenArmedForWake);

typedef EVT_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX_WITH_REASON *PFN_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX_WITH_REASON;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_SX)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_SX(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_SX *PFN_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_SX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_SX)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_SX(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_SX *PFN_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_SX;

typedef
_Function_class_(EVT_WDFCX_DEVICE_PRE_WAKE_FROM_SX_TRIGGERED)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_PRE_WAKE_FROM_SX_TRIGGERED(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_PRE_WAKE_FROM_SX_TRIGGERED *PFN_WDFCX_DEVICE_PRE_WAKE_FROM_SX_TRIGGERED;

typedef
_Function_class_(EVT_WDFCX_DEVICE_POST_WAKE_FROM_SX_TRIGGERED)
_IRQL_requires_same_
VOID
NTAPI
EVT_WDFCX_DEVICE_POST_WAKE_FROM_SX_TRIGGERED(
    _In_ WDFDEVICE Device);

typedef EVT_WDFCX_DEVICE_POST_WAKE_FROM_SX_TRIGGERED *PFN_WDFCX_DEVICE_POST_WAKE_FROM_SX_TRIGGERED;

typedef struct _WDFCX_POWER_POLICY_EVENT_CALLBACKS
{
    ULONG Size;
    PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0 EvtCxDevicePreArmWakeFromS0;
    PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_S0_FAILED_CLEANUP EvtCxDevicePreArmWakeFromS0FailedCleanup;
    PFN_WDFCX_DEVICE_POST_ARM_WAKE_FROM_S0 EvtCxDevicePostArmWakeFromS0;
    PFN_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_S0 EvtCxDevicePreDisarmWakeFromS0;
    PFN_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_S0 EvtCxDevicePostDisarmWakeFromS0;
    PFN_WDFCX_DEVICE_PRE_WAKE_FROM_S0_TRIGGERED EvtCxDevicePreWakeFromS0Triggered;
    PFN_WDFCX_DEVICE_POST_WAKE_FROM_S0_TRIGGERED EvtCxDevicePostWakeFromS0Triggered;
    PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX EvtCxDevicePreArmWakeFromSx;
    PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_FAILED_CLEANUP EvtCxDevicePreArmWakeFromSxFailedCleanup;
    PFN_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX EvtCxDevicePostArmWakeFromSx;
    PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON EvtCxDevicePreArmWakeFromSxWithReason;
    PFN_WDFCX_DEVICE_PRE_ARM_WAKE_FROM_SX_WITH_REASON_FAILED_CLEANUP EvtCxDevicePreArmWakeFromSxWithReasonFailedCleanup;
    PFN_WDFCX_DEVICE_POST_ARM_WAKE_FROM_SX_WITH_REASON EvtCxDevicePostArmWakeFromSxWithReason;
    PFN_WDFCX_DEVICE_PRE_DISARM_WAKE_FROM_SX EvtCxDevicePreDisarmWakeFromSx;
    PFN_WDFCX_DEVICE_POST_DISARM_WAKE_FROM_SX EvtCxDevicePostDisarmWakeFromSx;
    PFN_WDFCX_DEVICE_PRE_WAKE_FROM_SX_TRIGGERED EvtCxDevicePreWakeFromSxTriggered;
    PFN_WDFCX_DEVICE_POST_WAKE_FROM_SX_TRIGGERED EvtCxDevicePostWakeFromSxTriggered;
} WDFCX_POWER_POLICY_EVENT_CALLBACKS, *PWDFCX_POWER_POLICY_EVENT_CALLBACKS;

FORCEINLINE
VOID
WDFCX_POWER_POLICY_EVENT_CALLBACKS_INIT(
    _Out_ PWDFCX_POWER_POLICY_EVENT_CALLBACKS Callbacks)
{
    RtlZeroMemory(Callbacks, sizeof(*Callbacks));
    Callbacks->Size = sizeof(*Callbacks);
}

typedef
WDFAPI
VOID
(NTAPI *PFN_WDFCXDEVICEINITSETPNPPOWEREVENTCALLBACKS)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDFCX_PNPPOWER_EVENT_CALLBACKS CxPnpPowerCallbacks);

typedef
WDFAPI
VOID
(NTAPI *PFN_WDFCXDEVICEINITSETPOWERPOLICYEVENTCALLBACKS)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDFCX_POWER_POLICY_EVENT_CALLBACKS CxPowerPolicyCallbacks);

typedef
WDFAPI
NTSTATUS
(NTAPI *PFN_WDFCXDEVICEINITALLOCATECONTEXT)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFDEVICE_INIT DeviceInit,
    _In_ PWDF_OBJECT_ATTRIBUTES ContextAttributes,
    _Outptr_opt_ PVOID *Context);

typedef
WDFAPI
PVOID
(NTAPI *PFN_WDFCXDEVICEINITGETTYPEDCONTEXTWORKER)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFDEVICE_INIT DeviceInit,
    _In_ PCWDF_OBJECT_CONTEXT_TYPE_INFO TypeInfo);

/* What a class extension calls. The framework itself only fills the table. */

_Must_inspect_result_
_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
PWDFCXDEVICE_INIT
WdfCxDeviceInitAllocate(
    _In_ PWDFDEVICE_INIT DeviceInit)
{
    return ((PFN_WDFCXDEVICEINITALLOCATE)WdfFunctions[WdfCxDeviceInitAllocateTableIndex])(
        WdfDriverGlobals, DeviceInit);
}

_Must_inspect_result_
_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NTSTATUS
WdfCxDeviceInitAssignWdmIrpPreprocessCallback(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PFN_WDFCXDEVICE_WDM_IRP_PREPROCESS EvtCxDeviceWdmIrpPreprocess,
    _In_ UCHAR MajorFunction,
    _When_(NumMinorFunctions > 0, _In_reads_bytes_(NumMinorFunctions))
    _When_(NumMinorFunctions == 0, _In_opt_)
    PUCHAR MinorFunctions,
    _In_ ULONG NumMinorFunctions)
{
    return ((PFN_WDFCXDEVICEINITASSIGNWDMIRPPREPROCESSCALLBACK)WdfFunctions[WdfCxDeviceInitAssignWdmIrpPreprocessCallbackTableIndex])(
        WdfDriverGlobals, CxDeviceInit, EvtCxDeviceWdmIrpPreprocess, MajorFunction, MinorFunctions, NumMinorFunctions);
}

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
VOID
WdfCxDeviceInitSetIoInCallerContextCallback(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PFN_WDF_IO_IN_CALLER_CONTEXT EvtIoInCallerContext)
{
    ((PFN_WDFCXDEVICEINITSETIOINCALLERCONTEXTCALLBACK)WdfFunctions[WdfCxDeviceInitSetIoInCallerContextCallbackTableIndex])(
        WdfDriverGlobals, CxDeviceInit, EvtIoInCallerContext);
}

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
VOID
WdfCxDeviceInitSetRequestAttributes(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDF_OBJECT_ATTRIBUTES RequestAttributes)
{
    ((PFN_WDFCXDEVICEINITSETREQUESTATTRIBUTES)WdfFunctions[WdfCxDeviceInitSetRequestAttributesTableIndex])(
        WdfDriverGlobals, CxDeviceInit, RequestAttributes);
}

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
VOID
WdfCxDeviceInitSetFileObjectConfig(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDFCX_FILEOBJECT_CONFIG CxFileObjectConfig,
    _In_opt_ PWDF_OBJECT_ATTRIBUTES FileObjectAttributes)
{
    ((PFN_WDFCXDEVICEINITSETFILEOBJECTCONFIG)WdfFunctions[WdfCxDeviceInitSetFileObjectConfigTableIndex])(
        WdfDriverGlobals, CxDeviceInit, CxFileObjectConfig, FileObjectAttributes);
}

FORCEINLINE
VOID
WdfCxVerifierKeBugCheck(
    _In_opt_ WDFOBJECT Object,
    _In_ ULONG BugCheckCode,
    _In_ ULONG_PTR BugCheckParameter1,
    _In_ ULONG_PTR BugCheckParameter2,
    _In_ ULONG_PTR BugCheckParameter3,
    _In_ ULONG_PTR BugCheckParameter4)
{
    ((PFN_WDFCXVERIFIERKEBUGCHECK)WdfFunctions[WdfCxVerifierKeBugCheckTableIndex])(
        WdfDriverGlobals, Object, BugCheckCode, BugCheckParameter1, BugCheckParameter2, BugCheckParameter3, BugCheckParameter4);
}

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
VOID
WdfCxDeviceInitSetPnpPowerEventCallbacks(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDFCX_PNPPOWER_EVENT_CALLBACKS CxPnpPowerCallbacks)
{
    ((PFN_WDFCXDEVICEINITSETPNPPOWEREVENTCALLBACKS)WdfFunctions[WdfCxDeviceInitSetPnpPowerEventCallbacksTableIndex])(
        WdfDriverGlobals, CxDeviceInit, CxPnpPowerCallbacks);
}

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
VOID
WdfCxDeviceInitSetPowerPolicyEventCallbacks(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDFCX_POWER_POLICY_EVENT_CALLBACKS CxPowerPolicyCallbacks)
{
    ((PFN_WDFCXDEVICEINITSETPOWERPOLICYEVENTCALLBACKS)WdfFunctions[WdfCxDeviceInitSetPowerPolicyEventCallbacksTableIndex])(
        WdfDriverGlobals, CxDeviceInit, CxPowerPolicyCallbacks);
}

_Must_inspect_result_
_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NTSTATUS
WdfCxDeviceInitAllocateContext(
    _In_ PWDFDEVICE_INIT DeviceInit,
    _In_ PWDF_OBJECT_ATTRIBUTES ContextAttributes,
    _Outptr_opt_ PVOID *Context)
{
    return ((PFN_WDFCXDEVICEINITALLOCATECONTEXT)WdfFunctions[WdfCxDeviceInitAllocateContextTableIndex])(
        WdfDriverGlobals, DeviceInit, ContextAttributes, Context);
}

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
PVOID
WdfCxDeviceInitGetTypedContextWorker(
    _In_ PWDFDEVICE_INIT DeviceInit,
    _In_ PCWDF_OBJECT_CONTEXT_TYPE_INFO TypeInfo)
{
    return ((PFN_WDFCXDEVICEINITGETTYPEDCONTEXTWORKER)WdfFunctions[WdfCxDeviceInitGetTypedContextWorkerTableIndex])(
        WdfDriverGlobals, DeviceInit, TypeInfo);
}

#define WdfCxDeviceInitGetTypedContext(DeviceInit, ContextType) \
    ((ContextType *)WdfCxDeviceInitGetTypedContextWorker((DeviceInit), WDF_GET_CONTEXT_TYPE_INFO(ContextType)))

#endif /* _WDFCXBASE_H_ */
