1 stdcall -private GetDllVersion()
2 stdcall -private DllGetVersion (ptr)
3 stdcall Extract(ptr str)
4 stdcall -private DeleteExtractedFiles(ptr)
10 cdecl FCICreate(ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr)
11 cdecl FCIAddFile(long ptr ptr long ptr ptr ptr long)
12 cdecl FCIFlushFolder(long ptr ptr)
13 cdecl FCIFlushCabinet(long long ptr ptr)
14 cdecl FCIDestroy(long)
20 cdecl FDICreate(ptr ptr ptr ptr ptr ptr ptr long ptr)
21 cdecl FDIIsCabinet(long long ptr)
22 cdecl FDICopy(long ptr ptr long ptr ptr ptr)
23 cdecl FDIDestroy(long)
24 cdecl FDITruncateCabinet(long ptr long)
30 stdcall CreateCompressor(long ptr ptr)
31 stdcall SetCompressorInformation(ptr long ptr long)
32 stdcall QueryCompressorInformation(ptr long ptr long)
33 stdcall Compress(ptr ptr long ptr long ptr)
34 stdcall ResetCompressor(ptr)
35 stdcall CloseCompressor(ptr)
40 stdcall CreateDecompressor(long ptr ptr)
41 stdcall SetDecompressorInformation(ptr long ptr long)
42 stdcall QueryDecompressorInformation(ptr long ptr long)
43 stdcall Decompress(ptr ptr long ptr long ptr)
44 stdcall ResetDecompressor(ptr)
45 stdcall CloseDecompressor(ptr)
