/*
 * nvme.h
 *
 * NVM Express interface
 *
 * This file is part of the ReactOS PSDK package.
 *
 * THIS SOFTWARE IS NOT COPYRIGHTED
 *
 * This source code is offered for use in the public domain. You may
 * use, modify or distribute it freely.
 *
 * This code is distributed in the hope that it will be useful but
 * WITHOUT ANY WARRANTY. ALL WARRANTIES, EXPRESS OR IMPLIED ARE HEREBY
 * DISCLAIMED. This includes but is not limited to warranties of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

#ifndef _NVME_H_
#define _NVME_H_

#ifdef __cplusplus
extern "C" {
#endif

/* The admin queue always has identifier zero */
#define NVME_ADMINQ_ID                      0

#define NVME_NQN_MAX_LEN                    256
#define NVME_NQN_NAME_MAX_LEN               223

#define NVME_CONTROLLER_ID_MIN              0x0000
#define NVME_CONTROLLER_ID_MAX              0xFFEF
#define NVME_CONTROLLER_ID_STAT_PERSIST     0xFFFE
#define NVME_CONTROLLER_ID_DYN              0xFFFF

/* Identify Controller CNTRLTYPE */
typedef enum _NVME_CONTROLLER_TYPE
{
    NvmeCtrlNotReported = 0x00,
    NvmeCtrlIO = 0x01,
    NvmeCtrlDiscovery = 0x02,
    NvmeCtrlAdmin = 0x03,
    NvmeCtrlReservedMin = 0x04,
    NvmeCtrlReservedMax = 0xFF
} NVME_CONTROLLER_TYPE;

/* Byte offsets into the controller property region */
typedef enum _NVME_PROPERTY_OFFSET
{
    NvmePropCAP = 0x0000,
    NvmePropVS = 0x0008,
    NvmePropINTMS = 0x000C,
    NvmePropINTMC = 0x0010,
    NvmePropCC = 0x0014,
    NvmePropCSTS = 0x001C,
    NvmePropNSSR = 0x0020,
    NvmePropAQA = 0x0024,
    NvmePropASQ = 0x0028,
    NvmePropACQ = 0x0030,
    NvmePropCMBLOC = 0x0038,
    NvmePropCMBSZ = 0x003C,
    NvmePropBPINFO = 0x0040,
    NvmePropBPRSEL = 0x0044,
    NvmePropBPMBL = 0x0048,
    NvmePropCMBMSC = 0x0050,
    NvmePropCMBSTS = 0x0058,
    NvmePropCMBEBS = 0x005C,
    NvmePropCMBSWTP = 0x0060,
    NvmePropNSSD = 0x0064,
    NvmePropCRTO = 0x0068,
    NvmePropPMRCAP = 0x0E00,
    NvmePropPMRCTL = 0x0E04,
    NvmePropPMRSTS = 0x0E08,
    NvmePropPMREBS = 0x0E0C,
    NvmePropPMRSWTP = 0x0E10,
    NvmePropPMRMSCL = 0x0E14,
    NvmePropPMRMSCU = 0x0E18
} NVME_PROPERTY_OFFSET;

/* CAP.AMS and CC.AMS */
typedef enum
{
    NVME_AMS_ROUND_ROBIN = 0,
    NVME_AMS_WEIGHTED_ROUND_ROBIN_URGENT = 1
} NVME_AMS_OPTION;

/* CAP.CPS */
typedef enum
{
    NVME_CPS_NOT_REPORTED = 0,
    NVME_CPS_CONTROLLER_SCOPE = 1,
    NVME_CPS_DOMAIN_SCOPE = 2,
    NVME_CPS_SUBSYSTEM_SCOPE = 3
} NVME_CPS_VALUE;

/*
 * Offset 0x00, Controller Capabilities. Read only. TO counts 500ms units,
 * MPSMIN and MPSMAX are exponents of 4KB.
 */
typedef union
{
    struct
    {
        ULONGLONG MQES:16;
        ULONGLONG CQR:1;
        /* CAP.AMS occupies bits 17 and 18 */
        ULONGLONG AMS_WeightedRoundRobinWithUrgent:1;
        ULONGLONG AMS_VendorSpecific:1;
        ULONGLONG Reserved0:5;
        ULONGLONG TO:8;
        ULONGLONG DSTRD:4;
        ULONGLONG NSSRS:1;
        /* CAP.CSS occupies bits 37 to 44 */
        ULONGLONG CSS_NVM:1;
        ULONGLONG CSS_Reserved0:1;
        ULONGLONG CSS_Reserved1:1;
        ULONGLONG CSS_Reserved2:1;
        ULONGLONG CSS_Reserved3:1;
        ULONGLONG CSS_Reserved4:1;
        ULONGLONG CSS_MultipleIo:1;
        ULONGLONG CSS_AdminOnly:1;
        ULONGLONG BPS:1;
        ULONGLONG CPS:2;
        ULONGLONG MPSMIN:4;
        ULONGLONG MPSMAX:4;
        ULONGLONG PMRS:1;
        ULONGLONG CMBS:1;
        ULONGLONG NSSS:1;
        ULONGLONG CRWMS:1;
        ULONGLONG CRIMS:1;
        ULONGLONG Reserved2:3;
    } DUMMYSTRUCTNAME;
    ULONGLONG AsUlonglong;
} NVME_CONTROLLER_CAPABILITIES, *PNVME_CONTROLLER_CAPABILITIES;

/* Offset 0x08, Version */
typedef union
{
    struct
    {
        ULONG TER:8;
        ULONG MNR:8;
        ULONG MJR:16;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_VERSION, *PNVME_VERSION;

/* CC.SHN */
typedef enum
{
    NVME_CC_SHN_NO_NOTIFICATION = 0,
    NVME_CC_SHN_NORMAL_SHUTDOWN = 1,
    NVME_CC_SHN_ABRUPT_SHUTDOWN = 2
} NVME_CC_SHN_SHUTDOWN_NOTIFICATIONS;

/* CC.CSS */
typedef enum
{
    NVME_CSS_NVM_COMMAND_SET = 0,
    NVME_CSS_ALL_SUPPORTED_IO_COMMAND_SET = 6,
    NVME_CSS_ADMIN_COMMAND_SET_ONLY = 7
} NVME_CSS_COMMAND_SETS;

/*
 * Offset 0x14, Controller Configuration. MPS is an exponent of 4KB, IOSQES
 * and IOCQES are exponents of one byte.
 */
typedef union
{
    struct
    {
        ULONG EN:1;
        ULONG Reserved0:3;
        ULONG CSS:3;
        ULONG MPS:4;
        ULONG AMS:3;
        ULONG SHN:2;
        ULONG IOSQES:4;
        ULONG IOCQES:4;
        /* Writable only when CAP.CRMS allows it */
        ULONG CRIME:1;
        ULONG Reserved1:7;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_CONTROLLER_CONFIGURATION, *PNVME_CONTROLLER_CONFIGURATION;

/* CSTS.SHST */
typedef enum
{
    NVME_CSTS_SHST_NO_SHUTDOWN = 0,
    NVME_CSTS_SHST_SHUTDOWN_IN_PROCESS = 1,
    NVME_CSTS_SHST_SHUTDOWN_COMPLETED = 2
} NVME_CSTS_SHST_SHUTDOWN_STATUS;

/* Offset 0x1C, Controller Status. NSSRO is write one to clear. */
typedef union
{
    struct
    {
        ULONG RDY:1;
        ULONG CFS:1;
        ULONG SHST:2;
        ULONG NSSRO:1;
        ULONG PP:1;
        ULONG ST:1;
        ULONG Reserved0:25;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_CONTROLLER_STATUS, *PNVME_CONTROLLER_STATUS;

/* Offset 0x20, NVM Subsystem Reset */
typedef struct _NVME_NVM_SUBSYSTEM_RESET
{
    ULONG NSSRC;
} NVME_NVM_SUBSYSTEM_RESET, *PNVME_NVM_SUBSYSTEM_RESET;

/* Offset 0x24, Admin Queue Attributes. Both sizes are zero based. */
typedef union
{
    struct
    {
        ULONG ASQS:12;
        ULONG Reserved0:4;
        ULONG ACQS:12;
        ULONG Reserved1:4;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_ADMIN_QUEUE_ATTRIBUTES, *PNVME_ADMIN_QUEUE_ATTRIBUTES;

/* Offset 0x28, Admin Submission Queue Base Address */
typedef union
{
    struct
    {
        ULONGLONG Reserved0:12;
        ULONGLONG ASQB:52;
    } DUMMYSTRUCTNAME;
    ULONGLONG AsUlonglong;
} NVME_ADMIN_SUBMISSION_QUEUE_BASE_ADDRESS, *PNVME_ADMIN_SUBMISSION_QUEUE_BASE_ADDRESS;

/* Offset 0x30, Admin Completion Queue Base Address */
typedef union
{
    struct
    {
        ULONGLONG Reserved0:12;
        ULONGLONG ACQB:52;
    } DUMMYSTRUCTNAME;
    ULONGLONG AsUlonglong;
} NVME_ADMIN_COMPLETION_QUEUE_BASE_ADDRESS, *PNVME_ADMIN_COMPLETION_QUEUE_BASE_ADDRESS;

/* Offset 0x38, Controller Memory Buffer Location */
typedef union
{
    struct
    {
        ULONG BIR:3;
        ULONG Reserved:9;
        ULONG OFST:20;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_CONTROLLER_MEMORY_BUFFER_LOCATION, *PNVME_CONTROLLER_MEMORY_BUFFER_LOCATION;

/* CMBSZ.SZU */
typedef enum
{
    NVME_CMBSZ_SIZE_UNITS_4KB = 0,
    NVME_CMBSZ_SIZE_UNITS_64KB = 1,
    NVME_CMBSZ_SIZE_UNITS_1MB = 2,
    NVME_CMBSZ_SIZE_UNITS_16MB = 3,
    NVME_CMBSZ_SIZE_UNITS_256MB = 4,
    NVME_CMBSZ_SIZE_UNITS_4GB = 5,
    NVME_CMBSZ_SIZE_UNITS_64GB = 6
} NVME_CMBSZ_SIZE_UNITS;

/* Offset 0x3C, Controller Memory Buffer Size */
typedef union
{
    struct
    {
        ULONG SQS:1;
        ULONG CQS:1;
        ULONG LISTS:1;
        ULONG RDS:1;
        ULONG WDS:1;
        ULONG Reserved:3;
        ULONG SZU:4;
        ULONG SZ:20;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_CONTROLLER_MEMORY_BUFFER_SIZE, *PNVME_CONTROLLER_MEMORY_BUFFER_SIZE;

/* NSSD.NSSC, ASCII "Nrml" and "Abpt" */
#define NVM_SUBSYSTEM_SHUTDOWN_NORMAL       0x4E726D6C
#define NVM_SUBSYSTEM_SHUTDOWN_ABRUPT       0x41627074

/* Offset 0x64, NVM Subsystem Shutdown */
typedef struct _NVME_NVM_SUBSYSTEM_SHUTDOWN
{
    ULONG NSSC;
} NVME_NVM_SUBSYSTEM_SHUTDOWN, *PNVME_NVM_SUBSYSTEM_SHUTDOWN;

/* Offset 0x68, Controller Ready Timeouts. Both count 500ms units. */
typedef union _NVME_CONTROLLER_READY_TIMEOUTS
{
    struct
    {
        USHORT CRWMT;
        USHORT CRIMT;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_CONTROLLER_READY_TIMEOUTS, *PNVME_CONTROLLER_READY_TIMEOUTS;

/* Offset 0x1000 + 2y * (4 << CAP.DSTRD), Submission Queue y Tail Doorbell */
typedef union
{
    struct
    {
        ULONG SQT:16;
        ULONG Reserved0:16;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_SUBMISSION_QUEUE_TAIL_DOORBELL, *PNVME_SUBMISSION_QUEUE_TAIL_DOORBELL;

/* Offset 0x1000 + (2y + 1) * (4 << CAP.DSTRD), Completion Queue y Head Doorbell */
typedef union
{
    struct
    {
        ULONG CQH:16;
        ULONG Reserved0:16;
    } DUMMYSTRUCTNAME;
    ULONG AsUlong;
} NVME_COMPLETION_QUEUE_HEAD_DOORBELL, *PNVME_COMPLETION_QUEUE_HEAD_DOORBELL;

/*
 * The controller register block as it appears in BAR0. Doorbells begins the
 * doorbell array, whose stride comes from CAP.DSTRD.
 */
typedef struct
{
    NVME_CONTROLLER_CAPABILITIES CAP;
    NVME_VERSION VS;
    ULONG INTMS;
    ULONG INTMC;
    NVME_CONTROLLER_CONFIGURATION CC;
    ULONG Reserved0;
    NVME_CONTROLLER_STATUS CSTS;
    NVME_NVM_SUBSYSTEM_RESET NSSR;
    NVME_ADMIN_QUEUE_ATTRIBUTES AQA;
    NVME_ADMIN_SUBMISSION_QUEUE_BASE_ADDRESS ASQ;
    NVME_ADMIN_COMPLETION_QUEUE_BASE_ADDRESS ACQ;
    NVME_CONTROLLER_MEMORY_BUFFER_LOCATION CMBLOC;
    NVME_CONTROLLER_MEMORY_BUFFER_SIZE CMBSZ;
    /* 0x40 to 0x64 */
    ULONG Reserved1[9];
    NVME_NVM_SUBSYSTEM_SHUTDOWN NSSD;
    NVME_CONTROLLER_READY_TIMEOUTS CRTO;
    /* 0x6C to 0xEFF */
    ULONG Reserved2[933];
    /* 0xF00 to 0xFFF, command set specific */
    ULONG Reserved3[64];
    ULONG Doorbells[0];
} NVME_CONTROLLER_REGISTERS, *PNVME_CONTROLLER_REGISTERS;

/* Status field of a completion queue entry */
typedef union _NVME_COMMAND_STATUS
{
    struct
    {
        USHORT P:1;
        USHORT SC:8;
        USHORT SCT:3;
        USHORT CRD:2;
        USHORT M:1;
        USHORT DNR:1;
    } DUMMYSTRUCTNAME;
    USHORT AsUshort;
} NVME_COMMAND_STATUS, *PNVME_COMMAND_STATUS;

typedef struct
{
    ULONG DW0;
    ULONG DW1;
    union
    {
        struct
        {
            USHORT SQHD;
            USHORT SQID;
        } DUMMYSTRUCTNAME;
        ULONG AsUlong;
    } DW2;
    union
    {
        struct
        {
            USHORT CID;
            NVME_COMMAND_STATUS Status;
        } DUMMYSTRUCTNAME;
        ULONG AsUlong;
    } DW3;
} NVME_COMPLETION_ENTRY, *PNVME_COMPLETION_ENTRY;

/* NVME_COMMAND_STATUS.SCT */
typedef enum
{
    NVME_STATUS_TYPE_GENERIC_COMMAND = 0,
    NVME_STATUS_TYPE_COMMAND_SPECIFIC = 1,
    NVME_STATUS_TYPE_MEDIA_ERROR = 2,
    NVME_STATUS_TYPE_PATH_RELATED = 3,
    NVME_STATUS_TYPE_VENDOR_SPECIFIC = 7
} NVME_STATUS_TYPES;

/* NVME_COMMAND_STATUS.SC when SCT is NVME_STATUS_TYPE_GENERIC_COMMAND */
typedef enum
{
    NVME_STATUS_SUCCESS_COMPLETION = 0x00,
    NVME_STATUS_INVALID_COMMAND_OPCODE = 0x01,
    NVME_STATUS_INVALID_FIELD_IN_COMMAND = 0x02,
    NVME_STATUS_COMMAND_ID_CONFLICT = 0x03,
    NVME_STATUS_DATA_TRANSFER_ERROR = 0x04,
    NVME_STATUS_COMMAND_ABORTED_DUE_TO_POWER_LOSS_NOTIFICATION = 0x05,
    NVME_STATUS_INTERNAL_DEVICE_ERROR = 0x06,
    NVME_STATUS_COMMAND_ABORT_REQUESTED = 0x07,
    NVME_STATUS_COMMAND_ABORTED_DUE_TO_SQ_DELETION = 0x08,
    NVME_STATUS_COMMAND_ABORTED_DUE_TO_FAILED_FUSED_COMMAND = 0x09,
    NVME_STATUS_COMMAND_ABORTED_DUE_TO_FAILED_MISSING_COMMAND = 0x0A,
    NVME_STATUS_INVALID_NAMESPACE_OR_FORMAT = 0x0B,
    NVME_STATUS_COMMAND_SEQUENCE_ERROR = 0x0C,
    NVME_STATUS_INVALID_SGL_LAST_SEGMENT_DESCR = 0x0D,
    NVME_STATUS_INVALID_NUMBER_OF_SGL_DESCR = 0x0E,
    NVME_STATUS_DATA_SGL_LENGTH_INVALID = 0x0F,
    NVME_STATUS_METADATA_SGL_LENGTH_INVALID = 0x10,
    NVME_STATUS_SGL_DESCR_TYPE_INVALID = 0x11,
    NVME_STATUS_INVALID_USE_OF_CONTROLLER_MEMORY_BUFFER = 0x12,
    NVME_STATUS_PRP_OFFSET_INVALID = 0x13,
    NVME_STATUS_ATOMIC_WRITE_UNIT_EXCEEDED = 0x14,
    NVME_STATUS_OPERATION_DENIED = 0x15,
    NVME_STATUS_SGL_OFFSET_INVALID = 0x16,
    NVME_STATUS_RESERVED = 0x17,
    NVME_STATUS_HOST_IDENTIFIER_INCONSISTENT_FORMAT = 0x18,
    NVME_STATUS_KEEP_ALIVE_TIMEOUT_EXPIRED = 0x19,
    NVME_STATUS_KEEP_ALIVE_TIMEOUT_INVALID = 0x1A,
    NVME_STATUS_COMMAND_ABORTED_DUE_TO_PREEMPT_ABORT = 0x1B,
    NVME_STATUS_SANITIZE_FAILED = 0x1C,
    NVME_STATUS_SANITIZE_IN_PROGRESS = 0x1D,
    NVME_STATUS_SGL_DATA_BLOCK_GRANULARITY_INVALID = 0x1E,
    NVME_STATUS_COMMAND_NOT_SUPPORTED_FOR_QUEUE_IN_CMB = 0x1F,
    NVME_STATUS_NAMESPACE_IS_WRITE_PROTECTED = 0x20,
    NVME_STATUS_COMMAND_INTERRUPTED = 0x21,
    NVME_STATUS_TRANSIENT_TRANSPORT_ERROR = 0x22,
    NVME_STATUS_COMMAND_PROHIBITED_BY_LOCKDOWN = 0x23,
    NVME_STATUS_ADMIN_COMMAND_MEDIA_NOT_READY = 0x24,
    NVME_STATUS_DIRECTIVE_TYPE_INVALID = 0x70,
    NVME_STATUS_DIRECTIVE_ID_INVALID = 0x71,
    NVME_STATUS_NVM_LBA_OUT_OF_RANGE = 0x80,
    NVME_STATUS_NVM_CAPACITY_EXCEEDED = 0x81,
    NVME_STATUS_NVM_NAMESPACE_NOT_READY = 0x82,
    NVME_STATUS_NVM_RESERVATION_CONFLICT = 0x83,
    NVME_STATUS_FORMAT_IN_PROGRESS = 0x84
} NVME_STATUS_GENERIC_COMMAND_CODES;

/* NVME_COMMAND_STATUS.SC when SCT is NVME_STATUS_TYPE_COMMAND_SPECIFIC */
typedef enum
{
    NVME_STATUS_COMPLETION_QUEUE_INVALID = 0x00,
    NVME_STATUS_INVALID_QUEUE_IDENTIFIER = 0x01,
    NVME_STATUS_MAX_QUEUE_SIZE_EXCEEDED = 0x02,
    NVME_STATUS_ABORT_COMMAND_LIMIT_EXCEEDED = 0x03,
    NVME_STATUS_ASYNC_EVENT_REQUEST_LIMIT_EXCEEDED = 0x05,
    NVME_STATUS_INVALID_FIRMWARE_SLOT = 0x06,
    NVME_STATUS_INVALID_FIRMWARE_IMAGE = 0x07,
    NVME_STATUS_INVALID_INTERRUPT_VECTOR = 0x08,
    NVME_STATUS_INVALID_LOG_PAGE = 0x09,
    NVME_STATUS_INVALID_FORMAT = 0x0A,
    NVME_STATUS_FIRMWARE_ACTIVATION_REQUIRES_CONVENTIONAL_RESET = 0x0B,
    NVME_STATUS_INVALID_QUEUE_DELETION = 0x0C,
    NVME_STATUS_FEATURE_ID_NOT_SAVEABLE = 0x0D,
    NVME_STATUS_FEATURE_NOT_CHANGEABLE = 0x0E,
    NVME_STATUS_FEATURE_NOT_NAMESPACE_SPECIFIC = 0x0F,
    NVME_STATUS_FIRMWARE_ACTIVATION_REQUIRES_NVM_SUBSYSTEM_RESET = 0x10,
    NVME_STATUS_FIRMWARE_ACTIVATION_REQUIRES_RESET = 0x11,
    NVME_STATUS_FIRMWARE_ACTIVATION_REQUIRES_MAX_TIME_VIOLATION = 0x12,
    NVME_STATUS_FIRMWARE_ACTIVATION_PROHIBITED = 0x13,
    NVME_STATUS_OVERLAPPING_RANGE = 0x14,
    NVME_STATUS_NAMESPACE_INSUFFICIENT_CAPACITY = 0x15,
    NVME_STATUS_NAMESPACE_IDENTIFIER_UNAVAILABLE = 0x16,
    NVME_STATUS_NAMESPACE_ALREADY_ATTACHED = 0x18,
    NVME_STATUS_NAMESPACE_IS_PRIVATE = 0x19,
    NVME_STATUS_NAMESPACE_NOT_ATTACHED = 0x1A,
    NVME_STATUS_NAMESPACE_THIN_PROVISIONING_NOT_SUPPORTED = 0x1B,
    NVME_STATUS_CONTROLLER_LIST_INVALID = 0x1C,
    NVME_STATUS_DEVICE_SELF_TEST_IN_PROGRESS = 0x1D,
    NVME_STATUS_BOOT_PARTITION_WRITE_PROHIBITED = 0x1E,
    NVME_STATUS_INVALID_CONTROLLER_IDENTIFIER = 0x1F,
    NVME_STATUS_INVALID_SECONDARY_CONTROLLER_STATE = 0x20,
    NVME_STATUS_INVALID_NUMBER_OF_CONTROLLER_RESOURCES = 0x21,
    NVME_STATUS_INVALID_RESOURCE_IDENTIFIER = 0x22,
    NVME_STATUS_SANITIZE_PROHIBITED_ON_PERSISTENT_MEMORY = 0x23,
    NVME_STATUS_INVALID_ANA_GROUP_IDENTIFIER = 0x24,
    NVME_STATUS_ANA_ATTACH_FAILED = 0x25,
    NVME_STATUS_INSUFFICIENT_CAPACITY = 0x26,
    NVME_STATUS_NAMESPACE_ATTACHMENT_LIMIT_EXCEEDED = 0x27,
    NVME_STATUS_PROHIBITION_NOT_SUPPORTED = 0x28,
    NVME_IO_COMMAND_SET_NOT_SUPPORTED = 0x29,
    NVME_IO_COMMAND_SET_NOT_ENABLED = 0x2A,
    NVME_IO_COMMAND_SET_COMBINATION_REJECTED = 0x2B,
    NVME_IO_COMMAND_SET_INVALID = 0x2C,
    NVME_STATUS_INVALID_DISCOVERY_INFORMATION = 0x2F,
    NVME_STATUS_INSUFFICIENT_DISCOVERY_RESOURCES = 0x32,
    NVME_STATUS_STREAM_RESOURCE_ALLOCATION_FAILED = 0x7F,
    NVME_STATUS_ZONE_INVALID_FORMAT = 0x7F,
    NVME_STATUS_NVM_CONFLICTING_ATTRIBUTES = 0x80,
    NVME_STATUS_NVM_INVALID_PROTECTION_INFORMATION = 0x81,
    NVME_STATUS_NVM_ATTEMPTED_WRITE_TO_READ_ONLY_RANGE = 0x82,
    NVME_STATUS_NVM_COMMAND_SIZE_LIMIT_EXCEEDED = 0x83,
    NVME_STATUS_ZONE_BOUNDARY_ERROR = 0xB8,
    NVME_STATUS_ZONE_FULL = 0xB9,
    NVME_STATUS_ZONE_READ_ONLY = 0xBA,
    NVME_STATUS_ZONE_OFFLINE = 0xBB,
    NVME_STATUS_ZONE_INVALID_WRITE = 0xBC,
    NVME_STATUS_ZONE_TOO_MANY_ACTIVE = 0xBD,
    NVME_STATUS_ZONE_TOO_MANY_OPEN = 0xBE,
    NVME_STATUS_ZONE_INVALID_STATE_TRANSITION = 0xBF
} NVME_STATUS_COMMAND_SPECIFIC_CODES;

/* Command specific codes returned by the fabrics command set */
typedef enum
{
    NVME_STATUS_INCOMPATIBLE_FORMAT = 0x80,
    NVME_STATUS_CONTROLLER_BUSY = 0x81,
    NVME_STATUS_CONNECT_INVALID_PARAMETERS = 0x82,
    NVME_STATUS_CONNECT_RESTART_DISCOVERY = 0x83,
    NVME_STATUS_CONNECT_INVALID_HOST = 0x84,
    NVME_STATUS_INVALID_QUEUE_TYPE = 0x85,
    NVME_STATUS_DISCOVER_RESTART = 0x90,
    NVME_STATUS_AUTHENTICATION_REQUIRED = 0x91
} NVME_STATUS_FABRIC_COMMAND_CODES;

/* NVME_COMMAND_STATUS.SC when SCT is NVME_STATUS_TYPE_PATH_RELATED */
typedef enum
{
    NVME_STATUS_INTERNAL_PATH_ERROR = 0x00,
    NVME_STATUS_ASYMMETRIC_ACCESS_PERSISTENT_LOSS = 0x01,
    NVME_STATUS_ASYMMETRIC_ACCESS_INACCESSIBLE = 0x02,
    NVME_STATUS_ASYMMETRIC_ACCESS_TRANSITION = 0x03,
    NVME_STATUS_CONTROLLER_PATHING_ERROR = 0x60,
    NVME_STATUS_HOST_PATHING_ERROR = 0x70,
    NVME_STATUS_COMMAND_ABORTED_BY_HOST = 0x71
} NVME_STATUS_PATH_ERROR_CODES;

/* NVME_COMMAND_STATUS.SC when SCT is NVME_STATUS_TYPE_MEDIA_ERROR */
typedef enum
{
    NVME_STATUS_NVM_WRITE_FAULT = 0x80,
    NVME_STATUS_NVM_UNRECOVERED_READ_ERROR = 0x81,
    NVME_STATUS_NVM_END_TO_END_GUARD_CHECK_ERROR = 0x82,
    NVME_STATUS_NVM_END_TO_END_APPLICATION_TAG_CHECK_ERROR = 0x83,
    NVME_STATUS_NVM_END_TO_END_REFERENCE_TAG_CHECK_ERROR = 0x84,
    NVME_STATUS_NVM_COMPARE_FAILURE = 0x85,
    NVME_STATUS_NVM_ACCESS_DENIED = 0x86,
    NVME_STATUS_NVM_DEALLOCATED_OR_UNWRITTEN_LOGICAL_BLOCK = 0x87
} NVME_STATUS_MEDIA_ERROR_CODES;

typedef enum
{
    NVME_ADMIN_COMMAND_DELETE_IO_SQ = 0x00,
    NVME_ADMIN_COMMAND_CREATE_IO_SQ = 0x01,
    NVME_ADMIN_COMMAND_GET_LOG_PAGE = 0x02,
    NVME_ADMIN_COMMAND_DELETE_IO_CQ = 0x04,
    NVME_ADMIN_COMMAND_CREATE_IO_CQ = 0x05,
    NVME_ADMIN_COMMAND_IDENTIFY = 0x06,
    NVME_ADMIN_COMMAND_ABORT = 0x08,
    NVME_ADMIN_COMMAND_SET_FEATURES = 0x09,
    NVME_ADMIN_COMMAND_GET_FEATURES = 0x0A,
    NVME_ADMIN_COMMAND_ASYNC_EVENT_REQUEST = 0x0C,
    NVME_ADMIN_COMMAND_NAMESPACE_MANAGEMENT = 0x0D,
    NVME_ADMIN_COMMAND_FIRMWARE_ACTIVATE = 0x10,
    /* Renamed from Firmware Activate in spec revision 1.2 */
    NVME_ADMIN_COMMAND_FIRMWARE_COMMIT = 0x10,
    NVME_ADMIN_COMMAND_FIRMWARE_IMAGE_DOWNLOAD = 0x11,
    NVME_ADMIN_COMMAND_DEVICE_SELF_TEST = 0x14,
    NVME_ADMIN_COMMAND_NAMESPACE_ATTACHMENT = 0x15,
    NVME_ADMIN_COMMAND_KEEP_ALIVE = 0x18,
    NVME_ADMIN_COMMAND_DIRECTIVE_SEND = 0x19,
    NVME_ADMIN_COMMAND_DIRECTIVE_RECEIVE = 0x1A,
    NVME_ADMIN_COMMAND_VIRTUALIZATION_MANAGEMENT = 0x1C,
    NVME_ADMIN_COMMAND_NVME_MI_SEND = 0x1D,
    NVME_ADMIN_COMMAND_NVME_MI_RECEIVE = 0x1E,
    NVME_ADMIN_COMMAND_DISCOVERY_INFO_MGMT = 0x21,
    NVME_ADMIN_COMMAND_DOORBELL_BUFFER_CONFIG = 0x7C,
    NVME_ADMIN_COMMAND_FABRICS = 0x7F,
    NVME_ADMIN_COMMAND_FORMAT_NVM = 0x80,
    NVME_ADMIN_COMMAND_SECURITY_SEND = 0x81,
    NVME_ADMIN_COMMAND_SECURITY_RECEIVE = 0x82,
    NVME_ADMIN_COMMAND_SANITIZE = 0x84,
    NVME_ADMIN_COMMAND_GET_LBA_STATUS = 0x86
} NVME_ADMIN_COMMANDS;

typedef enum
{
    NVME_NVM_COMMAND_FLUSH = 0x00,
    NVME_NVM_COMMAND_WRITE = 0x01,
    NVME_NVM_COMMAND_READ = 0x02,
    NVME_NVM_COMMAND_WRITE_UNCORRECTABLE = 0x04,
    NVME_NVM_COMMAND_COMPARE = 0x05,
    NVME_NVM_COMMAND_WRITE_ZEROES = 0x08,
    NVME_NVM_COMMAND_DATASET_MANAGEMENT = 0x09,
    NVME_NVM_COMMAND_VERIFY = 0x0C,
    NVME_NVM_COMMAND_RESERVATION_REGISTER = 0x0D,
    NVME_NVM_COMMAND_RESERVATION_REPORT = 0x0E,
    NVME_NVM_COMMAND_RESERVATION_ACQUIRE = 0x11,
    NVME_NVM_COMMAND_RESERVATION_RELEASE = 0x15,
    NVME_NVM_COMMAND_COPY = 0x19,
    NVME_NVM_COMMAND_ZONE_MANAGEMENT_SEND = 0x79,
    NVME_NVM_COMMAND_ZONE_MANAGEMENT_RECEIVE = 0x7A,
    NVME_NVM_COMMAND_ZONE_APPEND = 0x7D
} NVME_NVM_COMMANDS;

C_ASSERT(sizeof(NVME_CONTROLLER_CAPABILITIES) == 8);
C_ASSERT(sizeof(NVME_COMPLETION_ENTRY) == 16);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, CC) == 0x14);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, CSTS) == 0x1C);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, AQA) == 0x24);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, ASQ) == 0x28);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, ACQ) == 0x30);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, NSSD) == 0x64);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, CRTO) == 0x68);
C_ASSERT(FIELD_OFFSET(NVME_CONTROLLER_REGISTERS, Doorbells) == 0x1000);

#ifdef __cplusplus
}
#endif

#endif /* _NVME_H_ */
