1 stdcall -stub RmAddFilter(long wstr ptr wstr long)
2 stdcall RmCancelCurrentTask(long)
3 stdcall RmEndSession(long)
4 stdcall -stub RmGetFilterList(long ptr long ptr)
5 stdcall RmGetList(long ptr ptr ptr ptr)
6 stdcall RmJoinSession(ptr wstr)
7 stdcall RmRegisterResources(long long ptr long ptr long ptr)
8 stdcall -stub RmRemoveFilter(long wstr ptr wstr)
9 stdcall -stub RmReserveHeap(long)
10 stdcall RmRestart(long long ptr)
11 stdcall RmShutdown(long long ptr)
12 stdcall RmStartSession(ptr long ptr)
