$if (_NTDDK_)

#define PTI_SHIFT 12
#define PDI_SHIFT 21

//
// ARM64 uses 4-level page tables with 4K pages
//
#define PTE_BASE 0xFFFFF68000000000ULL
#define PDE_BASE 0xFFFFF69000000000ULL
#define PPE_BASE 0xFFFFF6A000000000ULL
#define PXE_BASE 0xFFFFF6B000000000ULL

extern NTKERNELAPI PVOID MmHighestUserAddress;
extern NTKERNELAPI PVOID MmSystemRangeStart;
extern NTKERNELAPI ULONG64 MmUserProbeAddress;

#define MM_HIGHEST_USER_ADDRESS MmHighestUserAddress
#define MM_SYSTEM_RANGE_START MmSystemRangeStart
#if defined(_LOCAL_COPY_USER_PROBE_ADDRESS_)
#define MM_USER_PROBE_ADDRESS _LOCAL_COPY_USER_PROBE_ADDRESS_
extern ULONG _LOCAL_COPY_USER_PROBE_ADDRESS_;
#else
#define MM_USER_PROBE_ADDRESS MmUserProbeAddress
#endif
#define MM_LOWEST_USER_ADDRESS (PVOID)0x10000
#define MM_KSEG0_BASE       MM_SYSTEM_RANGE_START
#define MM_SYSTEM_SPACE_END 0xFFFFFFFFFFFFFFFFULL

$endif /* _NTDDK_ */
