include_directories(
    "wpa_supplicant"
    "src"
    "src/utils"
)

include_directories(
    "openssl-1.1.1w-uni/openssl-1.1/x86/includeopenssl"
    "openssl-1.1.1w-uni/openssl-1.1/x86/include"
)

set(COMMON_SOURCES
    "src/common/dragonfly.c"
    "src/common/hw_features_common.c"
    "src/common/ieee802_11_common.c"
    "src/common/ocv.c"
    "src/common/sae.c"
    "src/common/sae_pk.c"
    "src/common/wpa_common.c"
    "src/crypto/aes-ctr.c"
    "src/crypto/aes-ctr.c"
    "src/crypto/aes-eax.c"
    "src/crypto/aes-encblock.c"
    "src/crypto/aes-omac1.c"
    "src/crypto/aes-siv.c"
    "src/crypto/crypto_openssl.c"
    "src/crypto/dh_groups.c"
    "src/crypto/fips_prf_openssl.c"
    "src/crypto/ms_funcs.c"
    "src/crypto/random.c"
    "src/crypto/sha1-prf.c"
    "src/crypto/sha1-tlsprf.c"
    "src/crypto/sha1-tprf.c"
    "src/crypto/sha256-kdf.c"
    "src/crypto/sha256-prf.c"
    "src/crypto/sha256-tlsprf.c"
    "src/crypto/sha384-kdf.c"
    "src/crypto/sha384-prf.c"
    "src/crypto/sha512-kdf.c"
    "src/crypto/sha512-prf.c"
    "src/crypto/tls_openssl.c"
    "src/crypto/tls_openssl_ocsp.c"
    "src/drivers/driver_common.c"
    "src/drivers/driver_ndis.c"
    "src/drivers/driver_ndis_.c"
    "src/eap_common/chap.c"
    "src/eap_common/eap_common.c"
    "src/eap_common/eap_eke_common.c"
    "src/eap_common/eap_fast_common.c"
    "src/eap_common/eap_gpsk_common.c"
    "src/eap_common/eap_ikev2_common.c"
    "src/eap_common/eap_pax_common.c"
    "src/eap_common/eap_peap_common.c"
    "src/eap_common/eap_psk_common.c"
    "src/eap_common/eap_pwd_common.c"
    "src/eap_common/eap_sake_common.c"
    "src/eap_common/eap_sim_common.c"
    "src/eap_common/eap_wsc_common.c"
    "src/eap_common/ikev2_common.c"
    "src/eap_peer/eap.c"
    "src/eap_peer/eap_aka.c"
    "src/eap_peer/eap_eke.c"
    "src/eap_peer/eap_fast.c"
    "src/eap_peer/eap_fast_pac.c"
    "src/eap_peer/eap_gpsk.c"
    "src/eap_peer/eap_gtc.c"
    "src/eap_peer/eap_ikev2.c"
    "src/eap_peer/eap_leap.c"
    "src/eap_peer/eap_md5.c"
    "src/eap_peer/eap_methods.c"
    "src/eap_peer/eap_mschapv2.c"
    "src/eap_peer/eap_otp.c"
    "src/eap_peer/eap_pax.c"
    "src/eap_peer/eap_peap.c"
    "src/eap_peer/eap_psk.c"
    "src/eap_peer/eap_pwd.c"
    "src/eap_peer/eap_sake.c"
    "src/eap_peer/eap_sim.c"
    "src/eap_peer/eap_tls.c"
    "src/eap_peer/eap_tls_common.c"
    "src/eap_peer/eap_tnc.c"
    "src/eap_peer/eap_tnc.c"
    "src/eap_peer/eap_ttls.c"
    "src/eap_peer/eap_wsc.c"
    "src/eap_peer/ikev2.c"
    "src/eap_peer/mschapv2.c"
    "src/eap_peer/tncc.c"
    "src/eap_peer/tncc.c"
    "src/eapol_supp/eapol_supp_sm.c"
    "src/l2_packet/l2_packet_ndis.c"
    "src/pae/ieee802_1x_cp.c"
    "src/pae/ieee802_1x_kay.c"
    "src/pae/ieee802_1x_key.c"
    "src/pae/ieee802_1x_secy_ops.c"
    "src/rsn_supp/pmksa_cache.c"
    "src/rsn_supp/preauth.c"
    "src/rsn_supp/wpa.c"
    "src/rsn_supp/wpa_ie.c"
    "src/utils/base64.c"
    "src/utils/bitfield.c"
    "src/utils/common.c"
    "src/utils/config.c"
    "src/utils/crc32.c"
    "src/utils/eloop_win.c"
    "src/utils/ip_addr.c"
    "src/utils/os_win32.c"
    "src/utils/pcsc_funcs.c"
    "src/utils/uuid.c"
    "src/utils/wpabuf.c"
    "src/utils/wpa_debug.c"
    "src/wps/wps.c"
    "src/wps/wps_attr_build.c"
    "src/wps/wps_attr_parse.c"
    "src/wps/wps_attr_process.c"
    "src/wps/wps_common.c"
    "src/wps/wps_dev_attr.c"
    "src/wps/wps_enrollee.c"
    "src/wps/wps_registrar.c"
    "wpa_supplicant/autoscan.c"
    "wpa_supplicant/autoscan_exponential.c"
    "wpa_supplicant/autoscan_periodic.c"
    "wpa_supplicant/bgscan.c"
    "wpa_supplicant/bgscan_learn.c"
    "wpa_supplicant/bgscan_simple.c"
    "wpa_supplicant/bss.c"
    "wpa_supplicant/bssid_ignore.c"
    "wpa_supplicant/config.c"
    "wpa_supplicant/eap_register.c"
    "wpa_supplicant/events.c"
    "wpa_supplicant/notify.c"
    "wpa_supplicant/op_classes.c"
    "wpa_supplicant/robust_av.c"
    "wpa_supplicant/rrm.c"
    "wpa_supplicant/scan.c"
    "wpa_supplicant/twt.c"
    "wpa_supplicant/wmm_ac.c"
    "wpa_supplicant/wnm_sta.c"
    "wpa_supplicant/wpa_supplicant.c"
    "wpa_supplicant/wpas_glue.c"
    "wpa_supplicant/wpas_kay.c"
    "wpa_supplicant/wps_supplicant.c"
    "wpa_supplicant/ctrl_iface_named_pipe.c"
    "wpa_supplicant/ctrl_iface.c"
)


set(COMPILE_DEFINITIONS
    VERSION_STR_POSTFIX=" win32 port ${PORT_REVISION}-${WPAS_CTRL_IFACE}"
    GIT_VERSION_STR_POSTFIX="${GIT_VERSION_STR_POSTFIX}"
    CONFIG_FORCE_DHCP_RENEW
    CONFIG_L2_IP_IPHLPAPI
    CONFIG_NATIVE_WINDOWS
    CONFIG_ANSI_C_EXTRA
    CONFIG_WINPCAP
    IEEE8021X_EAPOL
    PKCS12_FUNCS
    PCSC_FUNCS
    CONFIG_DRIVER_NDIS
    CONFIG_USE_NDISUIO
    CONFIG_DEBUG_FILE
    EAP_MD5
    EAP_TLS
    EAP_MSCHAPv2
    EAP_PEAP
    EAP_TTLS
    EAP_GTC
    EAP_OTP
    EAP_SIM
    EAP_LEAP
    EAP_PSK
    EAP_AKA
    EAP_FAST
    EAP_PAX
    EAP_TNC
    EAP_TLS_OPENSSL
    CONFIG_SHA256
    CONFIG_NO_SOCKLEN_T_TYPEDEF
    TLS_DEFAULT_CIPHERS="ALL@SECLEVEL=0"
    _CRT_SECURE_NO_DEPRECATE
    CONFIG_WPS
    EAP_WSC
    EAP_PWD
    EAP_AKA_PRIME
    EAP_SAKE
    EAP_GPSK
    EAP_GPSK_SHA256
    CONFIG_ECC
    EAP_TNC
    EAP_IKEV2
    ALL_DH_GROUPS
    EAP_EKE
    CONFIG_MACSEC
    CONFIG_SMARTCARD
    CONFIG_SAE
    CONFIG_SAE_PK
    CONFIG_HMAC_SHA256_KDF
    CONFIG_BGSCAN
    CONFIG_BGSCAN_SIMPLE
    CONFIG_WEP
    CONFIG_HT_OVERRIDES
    CONFIG_VHT_OVERRIDES
    CONFIG_OCV
    CONFIG_TLSV11
    CONFIG_TLSV12
    CONFIG_DELAYED_MIC_ERROR_REPORT
    CONFIG_WNM
    CONFIG_AUTOSCAN_EXPONENTIAL
    CONFIG_AUTOSCAN_PERIODIC
    CONFIG_AUTOSCAN
    CONFIG_OWE
    CONFIG_HMAC_SHA384_KDF
    CONFIG_HMAC_SHA512_KDF
    CONFIG_SHA384
    CONFIG_SHA512
    CONFIG_SUITEB
    CONFIG_SUITEB192
    CONFIG_CTRL_IFACE_NAMED_PIPE
    CONFIG_BGSCAN_LEARN
)
list(APPEND COMPILE_DEFINITIONS CONFIG_CTRL_IFACE CONFIG_CTRL_IFACE_NAMED_PIPE)
add_executable(
    wpa_supplicant
    ${COMMON_SOURCES}
    "src/drivers/drivers.c"
    "wpa_supplicant/config_file.c"
    "wpa_supplicant/main.c"
)

target_compile_definitions(wpa_supplicant PRIVATE ${COMPILE_DEFINITIONS})
set_module_type(wpa_supplicant win32cui)
target_link_libraries(wpa_supplicant conutils ${PSEH_LIB})
target_link_libraries(wpa_supplicant "${CMAKE_SOURCE_DIR}/base/wifi/openssl-1.1.1w-uni/openssl-1.1/x86/lib/libcrypto.lib"
                                     "${CMAKE_SOURCE_DIR}/base/wifi/openssl-1.1.1w-uni/openssl-1.1/x86/lib/libssl.lib")
add_importlibs(wpa_supplicant winscard iphlpapi ws2_32 crypt32 advapi32 msvcrt kernel32 ntdll)
add_cd_file(TARGET wpa_supplicant DESTINATION reactos/system32 FOR all)


add_executable(
    win_if_list
    "wpa_supplicant/win_if_list.c"
)
target_compile_definitions(win_if_list PRIVATE ${COMPILE_DEFINITIONS})
set_module_type(win_if_list win32cui)
target_link_libraries(win_if_list conutils ${PSEH_LIB})
add_importlibs(win_if_list winscard iphlpapi ws2_32 crypt32 advapi32 msvcrt kernel32 ntdll)
add_cd_file(TARGET win_if_list DESTINATION reactos/system32 FOR all)
