@ stdcall DependentFSCheckFileHandle(ptr ptr long ptr ptr ptr ptr)
@ stdcall DependentFSCheckStoragePrivilege(ptr ptr long)
@ stdcall DependentFSDereferenceDependency(ptr)
@ stdcall DependentFSDismountForSystemEvent(long long ptr ptr)
@ stdcall DependentFSDismountForUnsurface(ptr ptr ptr ptr)
@ stdcall DependentFSGetVirtualStoragePolicies(long ptr ptr ptr ptr)
@ stdcall DependentFSReferenceDependency(ptr)
@ stdcall DependentFSRegister(ptr ptr ptr ptr long ptr long long ptr ptr long ptr)
@ stdcall DependentFSRegisterDeviceName(ptr ptr)
@ stdcall DependentFSUnregister(ptr ptr long ptr ptr)
