@ stdcall NmrClientAttachProvider(ptr ptr ptr ptr ptr)
@ stdcall NmrClientDetachProviderComplete(ptr)
@ stdcall NmrDeregisterClient(ptr)
@ stdcall NmrDeregisterProvider(ptr)
@ stdcall NmrProviderDetachClientComplete(ptr)
@ stdcall NmrRegisterClient(ptr ptr ptr)
@ stdcall NmrRegisterProvider(ptr ptr ptr)
@ stdcall NmrWaitForClientDeregisterComplete(ptr)
@ stdcall NmrWaitForProviderDeregisterComplete(ptr)
@ stdcall WskCaptureProviderNPI(ptr long ptr)
@ stdcall WskDeregister(ptr)
@ stdcall WskRegister(ptr ptr)
@ stdcall WskReleaseProviderNPI(ptr)
