/*
 * PROJECT:     ReactOS Simple Peripheral Bus
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     SpbCx controller object
 * COPYRIGHT:   Copyright 2026 Justin Miller <justinmiller100@gmail.com>
 */

/*
 * A controller driver calls SpbDeviceInitConfig on its WDFDEVICE_INIT before
 * WdfDeviceCreate, then SpbDeviceInitialize on the device afterwards. Between
 * them we take over the file-object and create paths, because a peripheral
 * reaching this device arrives as an open of a resource-hub name that only we
 * know how to parse.
 */

#define NDEBUG
#include "spbcxp.h"

static EVT_WDF_IO_QUEUE_IO_DEFAULT ScxEvtControllerIoDefault;
static EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL ScxEvtControllerIoDeviceControl;
static EVT_WDF_IO_QUEUE_IO_READ ScxEvtControllerIoRead;
static EVT_WDF_IO_QUEUE_IO_WRITE ScxEvtControllerIoWrite;

/*
 * A peripheral driver opens its controller in whatever context its own client
 * is running in, so the device has to be reachable by more than SYSTEM. The
 * reference applies the same DACL the resource hub uses.
 */
static
NTSTATUS
ScxDeviceInitSetDefaultDacl(
    _In_ PWDFDEVICE_INIT DeviceInit)
{
    DECLARE_CONST_UNICODE_STRING(DeviceSddl,
        L"D:P(A;;GA;;;SY)(A;;GA;;;BA)(A;;GA;;;UD)");

    /*
     * Ask for an automatic name before applying the security.
     *
     * KMDF refuses to create a device that carries an SDDL string or a
     * device class but has no name to apply it to - FxDeviceInit::HasName
     * is DeviceName != NULL || (Characteristics & FILE_AUTOGENERATED_DEVICE_NAME),
     * and WdfDeviceCreate returns STATUS_INVALID_SECURITY_DESCR when it is
     * false.  Nothing here or in the controller drivers names the device,
     * so every SPB controller failed to create with 0xC0000079 and took
     * its I2C, SPI and UART buses down with it.
     *
     * The reference does exactly this, in this order:
     * CScxController::_DeviceInitSetDefaultDacl calls
     * WdfDeviceInitSetCharacteristics(DeviceInit, 0x80, TRUE) and then
     * WdfDeviceInitAssignSDDLString - 0x80 being
     * FILE_AUTOGENERATED_DEVICE_NAME, which is what satisfies HasName().
     * Only the second of the two calls was carried across.
     */
    WdfDeviceInitSetCharacteristics(DeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);

    return WdfDeviceInitAssignSDDLString(DeviceInit, &DeviceSddl);
}

/*
 * Everything a peripheral does to a controller arrives through one of these
 * three, so they are set before the client gets its device:
 *
 *   IoInCallerContext  a transfer list points at the caller's buffers, so it has
 *                      to be captured while still in that process's context
 *   IrpPreprocess      IRP_MJ_CREATE carries the resource-hub name we parse the
 *                      connection id out of
 *   FileObjectConfig   each open becomes an SPBTARGET, cleaned up on close
 */
static
NTSTATUS
ScxDeviceInitSetDefaultCallbacks(
    _In_ PWDFCXDEVICE_INIT CxDeviceInit)
{
    WDFCX_FILEOBJECT_CONFIG FileObjectConfig;
    WDF_OBJECT_ATTRIBUTES FileObjectAttributes;
    NTSTATUS Status;

    WdfCxDeviceInitSetIoInCallerContextCallback(CxDeviceInit,
                                                ScxEvtIoInCallerContext);

    Status = WdfCxDeviceInitAssignWdmIrpPreprocessCallback(CxDeviceInit,
                                                           ScxEvtWdmIrpPreprocessCreate,
                                                           IRP_MJ_CREATE,
                                                           NULL,
                                                           0);
    if (!NT_SUCCESS(Status))
    {
        return Status;
    }

    RtlZeroMemory(&FileObjectConfig, sizeof(FileObjectConfig));
    FileObjectConfig.Size = sizeof(FileObjectConfig);
    FileObjectConfig.EvtCxDeviceFileCreate = ScxEvtDeviceFileCreate;
    FileObjectConfig.EvtFileClose = ScxEvtFileClose;
    FileObjectConfig.EvtFileCleanup = ScxEvtFileCleanup;
    FileObjectConfig.AutoForwardCleanupClose = WdfFalse;
    FileObjectConfig.FileObjectClass = WdfFileObjectWdfCanUseFsContext;

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&FileObjectAttributes, SCX_TARGET);

    WdfCxDeviceInitSetFileObjectConfig(CxDeviceInit,
                                       &FileObjectConfig,
                                       &FileObjectAttributes);

    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
ScxDeviceInitConfig(
    _In_ PSPB_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFDEVICE_INIT DeviceInit)
{
    PWDFCXDEVICE_INIT CxDeviceInit;
    NTSTATUS Status;

    PAGED_CODE();

    if (ScxGlobalsFromClient(DriverGlobals) == NULL || DeviceInit == NULL)
    {
        return STATUS_INVALID_PARAMETER;
    }

    Status = ScxDeviceInitSetDefaultDacl(DeviceInit);
    if (!NT_SUCCESS(Status))
    {
        return Status;
    }

    CxDeviceInit = WdfCxDeviceInitAllocate(DeviceInit);
    if (CxDeviceInit == NULL)
    {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    return ScxDeviceInitSetDefaultCallbacks(CxDeviceInit);
}

/*
 * The size check is the reference's: it rejects anything but the exact
 * SPB_CONTROLLER_CONFIG size rather than accepting a prefix, so a client built
 * against a different header fails here instead of reading past its own
 * structure. The reference hardcodes 72, its x64 sizeof.
 */
NTSTATUS
NTAPI
ScxDeviceInitialize(
    _In_ PSPB_DRIVER_GLOBALS DriverGlobals,
    _In_ WDFDEVICE FxDevice,
    _In_ PSPB_CONTROLLER_CONFIG Config)
{
    WDF_IO_QUEUE_CONFIG QueueConfig;
    WDF_OBJECT_ATTRIBUTES Attributes;
    PSCX_CONTROLLER Controller;
    NTSTATUS Status;

    PAGED_CODE();

    if (ScxGlobalsFromClient(DriverGlobals) == NULL ||
        FxDevice == NULL || Config == NULL)
    {
        return STATUS_INVALID_PARAMETER;
    }

    if (Config->Size != sizeof(SPB_CONTROLLER_CONFIG))
    {
        DPRINT1("SpbCx: SPB_CONTROLLER_CONFIG is %u bytes, client passed %u\n",
                (ULONG)sizeof(SPB_CONTROLLER_CONFIG), Config->Size);
        return STATUS_INFO_LENGTH_MISMATCH;
    }

    /* One controller per device; a second call is a client bug, not a reconfigure */
    if (ScxGetControllerContext(FxDevice) != NULL)
    {
        return STATUS_INVALID_PARAMETER;
    }

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&Attributes, SCX_CONTROLLER);

    Status = WdfObjectAllocateContext(FxDevice, &Attributes, (PVOID *)&Controller);
    if (!NT_SUCCESS(Status))
    {
        return Status;
    }

    RtlZeroMemory(Controller, sizeof(SCX_CONTROLLER));
    Controller->Device = FxDevice;
    Controller->Config = *Config;

    /*
     * The controller queue serializes transfers across every target, because the
     * bus itself is serial and two peripherals cannot be mid-transfer at once.
     * The client chooses the dispatch type only to say whether it wants requests
     * one at a time or presented in parallel for its own locking.
     */
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&QueueConfig, Config->ControllerDispatchType);
    QueueConfig.PowerManaged = Config->PowerManaged;
    QueueConfig.EvtIoDefault = ScxEvtControllerIoDefault;
    QueueConfig.EvtIoDeviceControl = ScxEvtControllerIoDeviceControl;
    QueueConfig.EvtIoInternalDeviceControl = ScxEvtControllerIoDeviceControl;
    QueueConfig.EvtIoRead = ScxEvtControllerIoRead;
    QueueConfig.EvtIoWrite = ScxEvtControllerIoWrite;

    WDF_OBJECT_ATTRIBUTES_INIT(&Attributes);
    Attributes.ExecutionLevel = WdfExecutionLevelPassive;

    Status = WdfIoQueueCreate(FxDevice,
                              &QueueConfig,
                              &Attributes,
                              &Controller->ControllerQueue);
    if (!NT_SUCCESS(Status))
    {
        DPRINT1("SpbCx: controller queue create failed 0x%08lX\n", Status);
        return Status;
    }

    return STATUS_SUCCESS;
}

/*
 * The reference keeps the IoOther callback out of SPB_CONTROLLER_CONFIG so that
 * a driver handling only the standard transfer IOCTLs never has to think about
 * it. Setting it also lets the client take over caller-context capture, which it
 * needs if its private IOCTLs carry buffers of their own.
 */
VOID
NTAPI
ScxControllerSetIoOtherCallback(
    _In_ PSPB_DRIVER_GLOBALS DriverGlobals,
    _In_ WDFDEVICE FxDevice,
    _In_opt_ PFN_SPB_CONTROLLER_OTHER EvtSpbControllerIoOther,
    _In_opt_ PFN_WDF_IO_IN_CALLER_CONTEXT EvtIoInCallerContext)
{
    PSCX_CONTROLLER Controller;

    if (ScxGlobalsFromClient(DriverGlobals) == NULL || FxDevice == NULL)
    {
        return;
    }

    Controller = ScxGetControllerContext(FxDevice);
    if (Controller == NULL)
    {
        return;
    }

    Controller->EvtSpbControllerIoOther = EvtSpbControllerIoOther;
    Controller->EvtIoInCallerContext = EvtIoInCallerContext;
}

VOID
NTAPI
ScxControllerSetRequestAttributes(
    _In_ PSPB_DRIVER_GLOBALS DriverGlobals,
    _In_ WDFDEVICE FxDevice,
    _In_ PWDF_OBJECT_ATTRIBUTES RequestAttributes)
{
    PSCX_CONTROLLER Controller;

    if (ScxGlobalsFromClient(DriverGlobals) == NULL ||
        FxDevice == NULL || RequestAttributes == NULL)
    {
        return;
    }

    Controller = ScxGetControllerContext(FxDevice);
    if (Controller == NULL)
    {
        return;
    }

    Controller->RequestAttributes = *RequestAttributes;
    Controller->RequestAttributesSet = TRUE;
}

VOID
NTAPI
ScxControllerSetTargetAttributes(
    _In_ PSPB_DRIVER_GLOBALS DriverGlobals,
    _In_ WDFDEVICE FxDevice,
    _In_ PWDF_OBJECT_ATTRIBUTES ObjectAttributes)
{
    PSCX_CONTROLLER Controller;

    if (ScxGlobalsFromClient(DriverGlobals) == NULL ||
        FxDevice == NULL || ObjectAttributes == NULL)
    {
        return;
    }

    Controller = ScxGetControllerContext(FxDevice);
    if (Controller == NULL)
    {
        return;
    }

    Controller->TargetAttributes = *ObjectAttributes;
    Controller->TargetAttributesSet = TRUE;
}

/*
 * Anything that is not one of the SPB IOCTLs, and anything arriving before a
 * target exists, is not something this extension can route.
 * CScxController::InvokeUnsupportedIo does the same.
 */
static
VOID
NTAPI
ScxEvtControllerIoDefault(
    _In_ WDFQUEUE Queue,
    _In_ WDFREQUEST Request)
{
    UNREFERENCED_PARAMETER(Queue);

    WdfRequestComplete(Request, STATUS_NOT_SUPPORTED);
}

/*
 * CScxController::ProcessRequest and the Invoke* family.
 *
 * Everything a peripheral asks of the bus arrives here and is turned into the
 * one callback in SPB_CONTROLLER_CONFIG that describes it. A client that did not
 * supply the callback for something is told it is unsupported rather than left
 * with a request it never sees.
 */
static
VOID
NTAPI
ScxEvtControllerIoDeviceControl(
    _In_ WDFQUEUE Queue,
    _In_ WDFREQUEST FxRequest,
    _In_ size_t OutputBufferLength,
    _In_ size_t InputBufferLength,
    _In_ ULONG IoControlCode)
{
    WDFDEVICE Device = WdfIoQueueGetDevice(Queue);
    PSCX_CONTROLLER Controller = ScxGetControllerContext(Device);
    PSCX_REQUEST Request;
    PSCX_TARGET Target;
    WDFFILEOBJECT FileObject;

    if (Controller == NULL)
    {
        WdfRequestComplete(FxRequest, STATUS_INVALID_DEVICE_REQUEST);
        return;
    }

    /*
     * The file object is the target: it is the handle the peripheral opened on
     * the resource-hub path, and target.c hung the connection off it.
     */
    FileObject = WdfRequestGetFileObject(FxRequest);
    if (FileObject == NULL)
    {
        WdfRequestComplete(FxRequest, STATUS_INVALID_DEVICE_REQUEST);
        return;
    }

    Target = ScxGetTargetContext(FileObject);
    if (Target == NULL || Target->ConnectionProperties == NULL)
    {
        /* An open that never resolved to a connection has no bus to talk to */
        WdfRequestComplete(FxRequest, STATUS_INVALID_DEVICE_REQUEST);
        return;
    }

    /*
     * Only a sequence was captured, so only a sequence has a request context.
     * The lock/unlock IOCTLs are handed straight through.
     */
    Request = ScxGetRequestContext(FxRequest);
    if (Request != NULL)
    {
        Request->Target = Target;
    }

    switch (IoControlCode)
    {
        case IOCTL_SPB_EXECUTE_SEQUENCE:
            if (Controller->Config.EvtSpbIoSequence == NULL || Request == NULL)
            {
                break;
            }

            Controller->Config.EvtSpbIoSequence(Device,
                                                (SPBTARGET)FileObject,
                                                (SPBREQUEST)FxRequest,
                                                Request->TransferCount);
            return;

        case IOCTL_SPB_LOCK_CONTROLLER:
            if (Controller->Config.EvtSpbControllerLock == NULL)
            {
                break;
            }

            Controller->Config.EvtSpbControllerLock(Device,
                                                    (SPBTARGET)FileObject,
                                                    (SPBREQUEST)FxRequest);
            return;

        case IOCTL_SPB_UNLOCK_CONTROLLER:
            if (Controller->Config.EvtSpbControllerUnlock == NULL)
            {
                break;
            }

            Controller->Config.EvtSpbControllerUnlock(Device,
                                                      (SPBTARGET)FileObject,
                                                      (SPBREQUEST)FxRequest);
            return;

        case IOCTL_SPB_LOCK_CONNECTION:
        case IOCTL_SPB_UNLOCK_CONNECTION:
            /*
             * A connection lock is per-target rather than per-controller. With
             * one target queue feeding one controller queue there is nothing yet
             * to serialize against, so acknowledge it: refusing would fail a
             * peripheral that brackets its transfers this way even though the
             * bracket is currently a no-op.
             */
            WdfRequestComplete(FxRequest, STATUS_SUCCESS);
            return;

        default:
            if (Controller->EvtSpbControllerIoOther != NULL)
            {
                Controller->EvtSpbControllerIoOther(Device,
                                                    (SPBTARGET)FileObject,
                                                    (SPBREQUEST)FxRequest,
                                                    OutputBufferLength,
                                                    InputBufferLength,
                                                    IoControlCode);
                return;
            }
            break;
    }

    WdfRequestComplete(FxRequest, STATUS_NOT_SUPPORTED);
}

/*
 * Reads and writes do not carry a transfer list, because WDF hands the buffer
 * over directly, so they reach the client without passing through capture.c.
 */
static
VOID
NTAPI
ScxEvtControllerIoRead(
    _In_ WDFQUEUE Queue,
    _In_ WDFREQUEST FxRequest,
    _In_ size_t Length)
{
    WDFDEVICE Device = WdfIoQueueGetDevice(Queue);
    PSCX_CONTROLLER Controller = ScxGetControllerContext(Device);
    WDFFILEOBJECT FileObject = WdfRequestGetFileObject(FxRequest);

    if (Controller == NULL || FileObject == NULL ||
        Controller->Config.EvtSpbIoRead == NULL ||
        ScxGetTargetContext(FileObject) == NULL)
    {
        WdfRequestComplete(FxRequest, STATUS_NOT_SUPPORTED);
        return;
    }

    Controller->Config.EvtSpbIoRead(Device,
                                    (SPBTARGET)FileObject,
                                    (SPBREQUEST)FxRequest,
                                    Length);
}

static
VOID
NTAPI
ScxEvtControllerIoWrite(
    _In_ WDFQUEUE Queue,
    _In_ WDFREQUEST FxRequest,
    _In_ size_t Length)
{
    WDFDEVICE Device = WdfIoQueueGetDevice(Queue);
    PSCX_CONTROLLER Controller = ScxGetControllerContext(Device);
    WDFFILEOBJECT FileObject = WdfRequestGetFileObject(FxRequest);

    if (Controller == NULL || FileObject == NULL ||
        Controller->Config.EvtSpbIoWrite == NULL ||
        ScxGetTargetContext(FileObject) == NULL)
    {
        WdfRequestComplete(FxRequest, STATUS_NOT_SUPPORTED);
        return;
    }

    Controller->Config.EvtSpbIoWrite(Device,
                                     (SPBTARGET)FileObject,
                                     (SPBREQUEST)FxRequest,
                                     Length);
}

