[FREELOADER]
DefaultOS=LiveImg_Debug
TimeOut=10

[Display]
TitleText=ReactOS Boot Media
MinimalUI=Yes

[Operating Systems]
Setup="ReactOS Setup (Text Mode)"
LiveImg="ReactOS Live Environment (Graphics Mode)"
LiveImg_RamDisk="ReactOS Live Environment - RamDisk"
==
;; The entries below are for testing and development:
Setup_Debug="Setup (Debug)"
Setup_SMP="Setup (SMP Debug)"
Setup_ACPI="Setup (ACPI PIC Debug)"
Setup_AAPIC="Setup (ACPI APIC UP Debug)"
Setup_Screen="Setup (Screen Debug)"
LiveImg_Debug="Live (Debug)"
LiveImg_SMP="Live (SMP Debug)"
LiveImg_RamDisk_SMP="Live RamDisk (SMP Debug)"
LiveImg_RamDisk_UP="Live RamDisk (UP Debug)"
LiveImg_RamDisk_AAPIC="Live RamDisk (ACPI APIC UP Debug)"
LiveImg_AAPIC="Live (ACPI APIC UP Debug)"
LiveImg_VBoxDebug="Live (VBox Debug)"
LiveImg_Screen="Live (Screen Debug)"
;; The following entry is an example template:
;LiveImg_LogFile="Live (Log file)"

[Setup]
BootType=ReactOSSetup

[Setup_Debug]
BootType=ReactOSSetup
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /NOGUIBOOT /SIFOPTIONSOVERRIDE

[Setup_SMP]
BootType=ReactOSSetup
Options=/KERNEL=NTKRNLMP.EXE /HAL=HALMACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /NOGUIBOOT /SIFOPTIONSOVERRIDE

[Setup_ACPI]
BootType=ReactOSSetup
Options=/KERNEL=NTOSKRNL.EXE /HAL=HALACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /NOGUIBOOT /SIFOPTIONSOVERRIDE

[Setup_AAPIC]
BootType=ReactOSSetup
Options=/KERNEL=NTOSKRNL.EXE /HAL=HALAACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /NOGUIBOOT /SIFOPTIONSOVERRIDE

[Setup_Screen]
BootType=ReactOSSetup
Options=/DEBUG /DEBUGPORT=SCREEN /SIFOPTIONSOVERRIDE

[LiveImg]
BootType=Windows2003
SystemPath=\reactos
Options=/FASTDETECT /MININT

[LiveImg_RamDisk]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/FASTDETECT /MININT /RDPATH=liveimg.iso /RDEXPORTASCD

[LiveImg_Debug]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=NET /HOST_IP=10.0.0.124 /HOST_PORT=50000 /ENCRYPTION_KEY=make.reactos.great.again /SOS /FASTDETECT /MININT

[LiveImg_SMP]
BootType=Windows2003
SystemPath=\reactos
Options=/KERNEL=NTKRNLMP.EXE /HAL=HALMACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT

[LiveImg_RamDisk_SMP]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=NTKRNLMP.EXE /HAL=HALMACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /RDPATH=liveimg.iso /RDEXPORTASCD

[LiveImg_RamDisk_UP]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=NTOSKRNL.EXE /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /RDPATH=liveimg.iso /RDEXPORTASCD

[LiveImg_RamDisk_AAPIC]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=NTOSKRNL.EXE /HAL=HALAACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /RDPATH=liveimg.iso /RDEXPORTASCD

[LiveImg_AAPIC]
BootType=Windows2003
SystemPath=\reactos
Options=/KERNEL=NTOSKRNL.EXE /HAL=HALAACPI.DLL /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT

[LiveImg_VBoxDebug]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=VBOX /SOS /FASTDETECT /MININT

[LiveImg_Screen]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=SCREEN /SOS /FASTDETECT /MININT

;[LiveImg_LogFile]
;BootType=Windows2003
;SystemPath=\reactos
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /FASTDETECT /MININT
